long_name = "Traducción al Español del Menú Principal"
short_name = "spanish"
for_module = "boot"
version = {1,0,0}
addon_version = {1,2,0}
weight = 6969
author = { "Ricard1974" }
homepage = "https://github.com/Ricard1974/tome4-es"
tags = { 'boot', 'espanol', 'spanish', 'translation' }
description = [[Traducción al español del menú principal de ToME4.]]
hooks = true
data = true
overload = true
superload = false
