long_name = "Spanish Translation for ToME"
short_name = "spanish"
for_module = "tome"
version = {1,7,6}
addon_version = {1,0,0}
tags = {'spanish', 'translation', 'español'}
weight = 10000000
author = { "Ricard1974", "ricard1974@example.com" }
homepage = "https://github.com/Ricard1974/tome4-es"
description = [[Traducción al español de Tales of Maj'Eyal (ToME4).]]
overload = true
data = true
hooks = true
