#!/usr/bin/env python3
"""
Traduce TODAS las cadenas restantes de engine.lua.
Última pasada para completar engine.lua.
"""

import re
from pathlib import Path

ENGINE = Path(__file__).parent.parent / "translations" / "es" / "engine.lua"

DICT = {
    "???": "???",
    "No": "No",
    "Error": "Error",
    "Global": "Global",
    "[spoilers]": "[spoilers]",
    "Select which channels to listen to. You can join new channels by typing '/join <channelname>' in the talkbox and leave channels by typing '/part <channelname>'": "Selecciona qué canales escuchar. Usa '/join <canal>' para unirte y '/part <canal>' para salir.",
    "      Press a key (escape to cancel, backspace to remove) for: %s": "Pulsa una tecla (escape=cancelar, retroceso=quitar) para: %s",
    "Make gesture (using right mouse button) or type it (or escape) for: %s": "Haz un gesto (clic derecho) o escríbelo (escape=cancelar) para: %s",
    "If you already reported that error, you do not have to do it again (unless you feel the situation is different).": "Si ya reportaste ese error, no hace falta que lo hagas de nuevo (a menos que creas que es diferente).",
    "You #LIGHT_GREEN#already reported#WHITE# that error, you do not have to do it again (unless you feel the situation is different).": "#LIGHT_GREEN#Ya reportaste#WHITE# ese error, no hace falta repetirlo (a menos que sea diferente).",
    "You have already got this error but #LIGHT_RED#never reported#WHITE# it, please do.": "Ya tuviste este error pero #LIGHT_RED#nunca lo reportaste#WHITE#, por favor hazlo.",
    "You have #LIGHT_RED#never seen#WHITE# that error, please report it.": "#LIGHT_RED#Nunca has visto#WHITE# este error, por favor repórtalo.",
    "Log saved to file (click to copy to clipboard):#LIGHT_BLUE#%s": "Log guardado (clic para copiar):#LIGHT_BLUE#%s",
    "Steam Cloud Purge": "Purgar nube de Steam",
    "Say: ": "Decir: ",
    "Target: ": "Objetivo: ",
    "Channel: %s": "Canal: %s",
    "Friend: %s": "Amigo: %s",
    "User: %s": "Usuario: %s",
    "Use Talents: ": "Usar talentos: ",
    "Talent": "Talento",
    "Game: ": "Juego: ",
    "Validation: ": "Validación: ",
    "Game has been validated by the server": "El juego ha sido validado por el servidor",
    "Game is not validated by the server": "El juego NO ha sido validado por el servidor",
    "Go to online profile": "Ir al perfil online",
    "Go to online charsheet": "Ir a la ficha online",
    "If you have a very high DPI screen you may want to raise this value. Requires a restart to take effect.#WHITE#": "Si tienes una pantalla de alto DPI, sube este valor. Requiere reiniciar.#WHITE#",
    "Enter Zoom %": "Introduce % de zoom",
    "From 50 to 400": "De 50 a 400",
    "Enter density": "Introduce densidad",
    "From 5 to 60": "De 5 a 60",
    "From 0 to 100": "De 0 a 100",
    "Font Scale %": "% de escala de fuente",
    "From 50 to 300": "De 50 a 300",
    "#GOLD##{bold}#Framebuffers#WHITE##{normal}#": "#GOLD##{bold}#Framebuffers#WHITE##{normal}#",
    "Gamma correction": "Corrección gamma",
    "Window Origin: X-Coordinate": "Origen ventana: Coordenada X",
    "Enter the x-coordinate": "Introduce la coordenada X",
    "Window Origin: Y-Coordinate": "Origen ventana: Coordenada Y",
    "Enter the y-coordinate": "Introduce la coordenada Y",
    "Position changed.": "Posición cambiada.",
    "Save position?": "¿Guardar posición?",
    "Revert": "Revertir",
    "High Scores": "Puntuaciones",
    "%s #GOLD#Purchasables#LAST#": "%s #GOLD#Comprables#LAST#",
    "Online Store": "Tienda online",
    "#{italic}##UMBER#Bonus vault slots from this order: #ROYAL_BLUE#%d#{normal}#": "#{italic}##UMBER#Espacios extra de bóveda: #ROYAL_BLUE#%d#{normal}#",
    "#{italic}##UMBER#Voratun Coins available from your donations: #ROYAL_BLUE#%d#{normal}#": "#{italic}##UMBER#Monedas Voratún disponibles: #ROYAL_BLUE#%d#{normal}#",
    "%s #GOLD#Online Store#LAST#": "%s #GOLD#Tienda online#LAST#",
    "Purchase": "Comprar",
    "Qty": "Cant",
    "You need to be logged in before using the store. Please go back to the main menu and login.": "Necesitas iniciar sesión para usar la tienda. Ve al menú principal e inicia sesión.",
    "Steam users need to link their profiles to their steam account. This is very easy in just a few clicks. Once this is done, simply restart the game.": "Los usuarios de Steam deben vincular su perfil. Es muy fácil en unos pocos clics. Luego reinicia el juego.",
    "Let's do it! (Opens in your browser)": "¡Hagámoslo! (Se abre en tu navegador)",
    "Not now": "Ahora no",
    "The Online Store (and expansions) are only purchasable by players that bought the game. Plaese go have a look at the donation page for more explanations.": "La tienda online y expansiones solo están disponibles para quienes compraron el juego. Visita la página de donaciones para más información.",
    "Let's go! (Opens in your browser)": "¡Vamos! (Se abre en tu navegador)",
    "%0.2f %s": "%0.2f %s",
    "#{bold}#TOTAL#{normal}#": "#{bold}#TOTAL#{normal}#",
    "  (%d items in cart, %s)": "  (%d artículos en carrito, %s)",
    "Shimmer pack installed!": "¡Paquete Shimmer instalado!",
    "Downloading cosmetic pack: #LIGHT_GREEN#%s": "Descargando paquete cosmético: #LIGHT_GREEN#%s",
    "- #{bold}##ROYAL_BLUE#%s #SLATE#x%d#WHITE##{normal}#: The pack should be downloading or even finished by now.": "- #{bold}##ROYAL_BLUE#%s #SLATE#x%d#WHITE##{normal}#: El paquete debería estar descargándose o ya terminó.",
    "- #{bold}##ROYAL_BLUE#%s #SLATE#x%d#WHITE##{normal}#: You can now trigger it whenever you are ready.": "- #{bold}##ROYAL_BLUE#%s #SLATE#x%d#WHITE##{normal}#: Puedes activarlo cuando quieras.",
    "- #{bold}##ROYAL_BLUE#%s #SLATE#x%d#WHITE##{normal}#: Your available vault space has increased.": "- #{bold}##ROYAL_BLUE#%s #SLATE#x%d#WHITE##{normal}#: Tu espacio de bóveda ha aumentado.",
    "Payment": "Pago",
    "Steam Overlay should appear, if it does not please make sure it you have not disabled it.": "Debería aparecer la superposición de Steam. Si no, asegúrate de no haberla desactivado.",
    "Finalizing transaction with Steam servers...": "Finalizando transacción con servidores de Steam...",
    "New Achievement": "Nuevo logro",
    "Mouse Gestures": "Gestos de ratón",
    "Running...": "Ejecutando...",
    "Please wait...": "Espera por favor...",
    "Game installed!": "¡Juego instalado!",
    "Item not found": "Objeto no encontrado",
    "Hotkey not defined": "Tecla no definida",
    "a ": "un ",
    "an ": "un ",
    "activates": "activa",
    "deactivates": "desactiva",
    "didn't move": "no se movió",
    "Target yourself?": "¿Apuntarte a ti mismo?",
    "Saving...": "Guardando...",
    "Payment refused, you have not been billed.": "Pago rechazado, no se te ha cobrado.",
    "You have enough coins to instantly purchase those options. Confirm?": "Tienes suficientes monedas para comprar esas opciones. ¿Confirmar?",
    "%s #GOLD#Purchased Options#LAST#": "%s #GOLD#Opciones compradas#LAST#",
    "Please use purchased options when not on the worldmap.": "Usa las opciones compradas cuando no estés en el mapa mundial.",
    "This option may only be used once per character to prevent wasting it.": "Esta opción solo puede usarse una vez por personaje.",
    "This pack is already installed and in use for your character.": "Este paquete ya está instalado y en uso.",
    "Please wait while contacting the server...": "Espera mientras contactamos con el servidor...",
    "The option has been activated.": "La opción ha sido activada.",
    "There was an error from the server: %s": "Hubo un error del servidor: %s",
    "You have not purchased any usable options yet. Would you like to see the store?": "Aún no has comprado opciones. ¿Quieres ver la tienda?",
    "wrong equipment slot": "espacio de equipo incorrecto",
    "not enough stat": "atributo insuficiente",
    "missing %s (level %s )": "falta %s (nivel %s)",
    "missing %s": "falta %s",
    "not enough levels": "niveles insuficientes",
    "missing dependency": "dependencia faltante",
    "cannot use currently due to an other worn object": "no se puede usar por otro objeto equipado",
    "%s is not wearable.": "%s no es equipable.",
    "%s can not wear %s.": "%s no puede equipar %s.",
    "%s can not wear (%s): %s (%s).": "%s no puede equipar (%s): %s (%s).",
    "%s wears (offslot): %s.": "%s equipa (secundario): %s.",
    "%s wears (replacing %s): %s.": "%s equipa (reemplazando %s): %s.",
    "%s can not wear: %s.": "%s no puede equipar: %s.",
    "something": "algo",
    "%s attacks %s.": "%s ataca a %s.",
    "wrong slot": "espacio incorrecto",
    "not enough %s": "%s insuficiente",
    "this item belongs to someone else": "este objeto pertenece a otro",
    "the chest is empty": "el cofre está vacío",
    "the chest is locked": "el cofre está cerrado",
    "the container is empty": "el contenedor está vacío",
    "You can not use this while running.": "No puedes usar esto mientras corres.",
    "You can not use this while resting.": "No puedes usar esto mientras descansas.",
    "You can not use this while exploring.": "No puedes usar esto mientras exploras.",
    "You can not use this while auto-exploring": "No puedes usar esto mientras autoexploras",
    "message": "mensaje",
    "Player": "Jugador",
    "Players": "Jugadores",
    "Gender": "Género",
    "Male": "Masculino",
    "Female": "Femenino",
    "Tactical display enabled. Press shift+'t' to disable.": "Pantalla táctica activada. Presiona shift+'t' para desactivar.",
    "Tactical display disabled. Press shift+'t' to enable.": "Pantalla táctica desactivada. Presiona shift+'t' para activar.",
    "Error report sent, thank you.": "Informe de error enviado, gracias.",
    "#YELLOW#Error report sent, thank you.": "#YELLOW#Informe de error enviado, gracias.",
    "Game installation successful. Have fun!": "Instalación completada. ¡Diviértete!",
    "Talent Use Confirmation": "Confirmación de uso de talento",
    "URL copied to your clipboard.": "URL copiada al portapapeles.",
    "Use %s?": "¿Usar %s?",
    "You are %s, press Enter to stop.": "Estás %s, presiona Enter para parar.",
    "You are exploring, press any key to stop.": "Estás explorando, presiona cualquier tecla para parar.",
    "You are running, press Enter to stop.": "Estás corriendo, presiona Enter para parar.",
    "You are running, press any key to stop.": "Estás corriendo, presiona cualquier tecla para parar.",
    "You do not have any %s .": "No tienes ningún %s.",
    "at %s": "en %s",
    "is not %s": "no está %s",
    "not enough stat: %s": "atributo insuficiente: %s",
    "not enough talents of this type known": "no hay suficientes talentos de este tipo conocidos",
    "- Is %s": "- Es %s",
    "- Level %d": "- Nivel %d",
    "- Lower talents of the same category: %d": "- Talentos inferiores de la misma categoría: %d",
    "- Talent %s": "- Talento %s",
    "- Talent %s (%d)": "- Talento %s (%d)",
    "- Talent %s (not known)": "- Talento %s (no conocido)",
    "It can be used to %s, costing %d power out of %d/%d.": "Se puede usar para %s, costando %d de poder de %d/%d.",
    "It can be used to %s, with %d charges out of %d.": "Se puede usar para %s, con %d cargas de %d.",
    "It can be used to activate talent: %s (level %d).": "Se puede usar para activar talento: %s (nivel %d).",
    "Ran for %d turns (stop reason: %s).": "Corrió durante %d turnos (motivo: %s).",
    "rested": "descansado",
    "resting": "descansando",
    "terrain change on the left": "cambio de terreno a la izquierda",
    "terrain change on the right": "cambio de terreno a la derecha",
    "the path is blocked": "el camino está bloqueado",
    "trap spotted": "trampa detectada",
    "unknown talent type": "tipo de talento desconocido",
    "he": "él",
    "him": "él",
    "his": "su",
    "himself": "sí mismo",
    "she": "ella",
    "her": "ella",
    "herself": "sí misma",
    "it": "ello",
    "its": "su",
    "itself": "sí mismo",
    "%s...": "%s...",
    "%s %s %s.": "%s %s %s.",
}


def main():
    with open(ENGINE, "r", encoding="utf-8") as f:
        content = f.read()

    count = 0
    for orig, trans in sorted(DICT.items(), key=lambda x: -len(x[0])):
        old = f't("{orig}", "{orig}",'
        new = f't("{orig}", "{trans}",'
        if old in content:
            content = content.replace(old, new)
            count += 1

    with open(ENGINE, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"✅ engine.lua: +{count} traducciones")
    print()

    # Mostrar cuántas quedan
    remaining = len(re.findall(r't\("([^"]*)",\s*"\1"', content))
    print(f"📊 Quedan {remaining} sin traducir en engine.lua")


if __name__ == "__main__":
    main()
