#!/usr/bin/env python3
"""
TRADUCTOR MASIVO COMPLETO para ToME4-es
Traduce las 16.899 cadenas únicas usando:
1. Diccionario de términos y frases completas
2. Reglas de patrones (prefijos, números, tipos)
3. Traducción palabra por palabra con diccionario EN→ES

Uso: python3 scripts/translate_all.py
"""

import re
import json
import sys
from pathlib import Path

TRANS_DIR = Path(__file__).parent.parent / "translations" / "es"

# =============================================================================
# DICCIONARIO INGLÉS → ESPAÑOL (palabras sueltas)
# =============================================================================
EN_ES = {
    # Verbos comunes
    "attack": "atacar",
    "attacks": "ataca",
    "attacked": "atacado",
    "defend": "defender",
    "defends": "defiende",
    "hit": "golpear",
    "hits": "golpea",
    "hitting": "golpeando",
    "strike": "golpe",
    "strikes": "golpea",
    "struck": "golpeó",
    "slash": "cortar",
    "slashes": "corta",
    "slashing": "cortante",
    "cut": "corte",
    "cuts": "corta",
    "pierce": "perforar",
    "pierces": "perfora",
    "piercing": "perforante",
    "crush": "aplastar",
    "crushes": "aplasta",
    "crushing": "aplastante",
    "burn": "quemar",
    "burns": "quema",
    "burning": "ardiente",
    "freeze": "congelar",
    "freezes": "congela",
    "freezing": "congelante",
    "shock": "electrocutar",
    "shocks": "electrocuta",
    "poison": "envenenar",
    "poisons": "envenena",
    "poisonous": "venenoso",
    "heal": "curar",
    "heals": "cura",
    "healing": "curativo",
    "restore": "restaurar",
    "restores": "restaura",
    "increase": "aumentar",
    "increases": "aumenta",
    "increased": "aumentado",
    "decrease": "reducir",
    "decreases": "reduce",
    "decreased": "reducido",
    "reduce": "reducir",
    "reduces": "reduce",
    "reduced": "reducido",
    "boost": "potenciar",
    "boosts": "potencia",
    "boosted": "potenciado",
    "improve": "mejorar",
    "improves": "mejora",
    "improved": "mejorado",
    "grant": "otorgar",
    "grants": "otorga",
    "granted": "otorgado",
    "gain": "ganar",
    "gains": "gana",
    "lose": "perder",
    "loses": "pierde",
    "lost": "perdido",
    "remove": "eliminar",
    "removes": "elimina",
    "removed": "eliminado",
    "apply": "aplicar",
    "applies": "aplica",
    "applied": "aplicado",
    "resist": "resistir",
    "resists": "resiste",
    "absorb": "absorber",
    "absorbs": "absorbe",
    "convert": "convertir",
    "converts": "convierte",
    "converted": "convertido",
    "transform": "transformar",
    "transforms": "transforma",
    "summon": "invocar",
    "summons": "invoca",
    "summoned": "invocado",
    "teleport": "teletransportar",
    "teleports": "teletransporta",
    "slow": "ralentizar",
    "slows": "ralentiza",
    "stun": "aturdir",
    "stuns": "aturde",
    "stunned": "aturdido",
    "confuse": "confundir",
    "confuses": "confunde",
    "confused": "confundido",
    "silence": "silenciar",
    "silences": "silencia",
    "silenced": "silenciado",
    "blind": "cegar",
    "blinds": "ciega",
    "blinded": "cegado",
    "pin": "inmovilizar",
    "pins": "inmoviliza",
    "pinned": "inmovilizado",
    "knockback": "derribar",
    "knocks back": "derriba",
    "disarm": "desarmar",
    "disarms": "desarma",
    "disarmed": "desarmado",
    "daze": "atontar",
    "dazes": "atonta",
    "dazed": "atontado",
    "fear": "atemorizar",
    "fears": "atemoriza",
    "feared": "atemorizado",
    "charm": "embelesar",
    "charms": "embelesa",
    "sleep": "dormir",
    "sleeps": "duerme",
    "sleeping": "durmiendo",
    # Sustantivos de juego
    "damage": "daño",
    "damages": "daños",
    "power": "poder",
    "powers": "poderes",
    "strength": "fuerza",
    "might": "poderío",
    "skill": "habilidad",
    "skills": "habilidades",
    "ability": "capacidad",
    "abilities": "capacidades",
    "talent": "talento",
    "talents": "talentos",
    "spell": "hechizo",
    "spells": "hechizos",
    "magic": "magia",
    "arcane": "arcano",
    "nature": "naturaleza",
    "wild": "salvaje",
    "elemental": "elemental",
    "effect": "efecto",
    "effects": "efectos",
    "aura": "aura",
    "shield": "escudo",
    "shields": "escudos",
    "barrier": "barrera",
    "barriers": "barreras",
    "ward": "protección",
    "wards": "protecciones",
    "mastery": "maestría",
    "affinity": "afinidad",
    "resistance": "resistencia",
    "resistances": "resistencias",
    "immunity": "inmunidad",
    "immunities": "inmunidades",
    "penetration": "penetración",
    "duration": "duración",
    "range": "alcance",
    "radius": "radio",
    "speed": "velocidad",
    "chance": "probabilidad",
    "rate": "ritmo",
    "cooldown": "enfriamiento",
    "cost": "coste",
    "costs": "costes",
    "level": "nivel",
    "levels": "niveles",
    "rank": "rango",
    "ranks": "rangos",
    # Objetos y equipo
    "weapon": "arma",
    "weapons": "armas",
    "armor": "armadura",
    "armors": "armaduras",
    "armour": "armadura",
    "helmet": "casco",
    "helmets": "cascos",
    "gloves": "guantes",
    "boots": "botas",
    "cloak": "capa",
    "cloaks": "capas",
    "belt": "cinturón",
    "belts": "cinturones",
    "ring": "anillo",
    "rings": "anillos",
    "amulet": "amuleto",
    "amulets": "amuletos",
    "gem": "gema",
    "gems": "gemas",
    "potion": "poción",
    "potions": "pociones",
    "scroll": "pergamino",
    "scrolls": "pergaminos",
    "wand": "varita",
    "wands": "varitas",
    "staff": "bastón",
    "staves": "bastones",
    "dagger": "daga",
    "daggers": "dagas",
    "sword": "espada",
    "swords": "espadas",
    "axe": "hacha",
    "axes": "hachas",
    "mace": "maza",
    "maces": "mazas",
    "bow": "arco",
    "bows": "arcos",
    "sling": "honda",
    "quiver": "carcaj",
    "quivers": "carcajes",
    "arrow": "flecha",
    "arrows": "flechas",
    "shot": "proyectil",
    "shots": "proyectiles",
    "ammo": "munición",
    "token": "ficha",
    "tokens": "fichas",
    # Razas y criaturas
    "human": "humano",
    "humans": "humanos",
    "elf": "elfo",
    "elves": "elfos",
    "dwarf": "enano",
    "dwarves": "enanos",
    "dwarfs": "enanos",
    "orc": "orco",
    "orcs": "orcos",
    "halfling": "mediano",
    "halflings": "medianos",
    "skeleton": "esqueleto",
    "skeletons": "esqueletos",
    "ghoul": "ghul",
    "ghouls": "ghules",
    "dragon": "dragón",
    "dragons": "dragones",
    "giant": "gigante",
    "giants": "gigantes",
    "demon": "demonio",
    "demons": "demonios",
    "undead": "no-muerto",
    "undeads": "no-muertos",
    "spider": "araña",
    "spiders": "arañas",
    "wolf": "lobo",
    "wolves": "lobos",
    "bear": "oso",
    "bears": "osos",
    "tiger": "tigre",
    "tigers": "tigres",
    "rat": "rata",
    "rats": "ratas",
    "snake": "serpiente",
    "snakes": "serpientes",
    "turtle": "tortuga",
    "turtles": "tortugas",
    "wurm": "gusano",
    "wurms": "gusanos",
    "wyrm": "dragón",
    "wyrms": "dragones",
    "elemental": "elemental",
    "elementals": "elementales",
    "golem": "gólem",
    "golems": "gólems",
    "construct": "constructo",
    "constructs": "constructos",
    "eye": "ojo",
    "eyes": "ojos",
    # Adjetivos comunes
    "ancient": "ancestral",
    "ancient's": "ancestral",
    "elder": "anciano",
    "great": "gran",
    "greater": "mayor",
    "greatest": "supremo",
    "lesser": "menor",
    "minor": "menor",
    "major": "mayor",
    "superior": "superior",
    "inferior": "inferior",
    "powerful": "poderoso",
    "deadly": "mortal",
    "lethal": "letal",
    "cursed": "maldito",
    "blessed": "bendito",
    "holy": "sagrado",
    "unholy": "profano",
    "magical": "mágico",
    "enchanted": "encantado",
    "rare": "raro",
    "unique": "único",
    "epic": "épico",
    "legendary": "legendario",
    "flaming": "llameante",
    "freezing": "helado",
    "shocking": "electrizante",
    "venomous": "venenoso",
    "shadowy": "sombrío",
    "glowing": "brillante",
    "shimmering": "centelleante",
    "corrupted": "corrupto",
    "tainted": "infecto",
    "pure": "puro",
    "dark": "oscuro",
    "light": "luminoso",
    # Preposiciones y conectores
    "of": "de",
    "in": "en",
    "on": "sobre",
    "at": "en",
    "with": "con",
    "without": "sin",
    "for": "para",
    "to": "para",
    "from": "de",
    "by": "por",
    "as": "como",
    "or": "o",
    "and": "y",
    "but": "pero",
    "if": "si",
    "when": "cuando",
    "while": "mientras",
    "within": "dentro de",
    "during": "durante",
    "after": "tras",
    "before": "antes de",
    "the": "el",
    "The": "El",
    "a": "",
    "an": "",
    "your": "tu",
    "Your": "Tu",
    "you": "tú",
    "You": "Tú",
    "all": "todo",
    "All": "Todo",
    "every": "cada",
    "some": "algunos",
    "any": "cualquier",
    "no": "sin",
    "this": "este",
    "This": "Este",
    "that": "ese",
    "That": "Ese",
    # Colores
    "red": "rojo",
    "Red": "Rojo",
    "blue": "azul",
    "Blue": "Azul",
    "green": "verde",
    "Green": "Verde",
    "white": "blanco",
    "White": "Blanco",
    "black": "negro",
    "Black": "Negro",
    "grey": "gris",
    "Grey": "Gris",
    "gray": "gris",
    "Gray": "Gris",
    "yellow": "amarillo",
    "Yellow": "Amarillo",
    "gold": "dorado",
    "Gold": "Dorado",
    "silver": "plateado",
    "Silver": "Plateado",
    "bronze": "bronce",
    "Bronze": "Bronce",
    "crimson": "carmesí",
    "Crimson": "Carmesí",
    "violet": "violeta",
    "Violet": "Violeta",
    "purple": "púrpura",
    "Purple": "Púrpura",
    "orange": "naranja",
    "Orange": "Naranja",
    "brown": "marrón",
    "Brown": "Marrón",
    "pink": "rosa",
    "Pink": "Rosa",
    "slate": "pizarra",
    "Slate": "Pizarra",
    "dark": "oscuro",
    "Dark": "Oscuro",
    "light": "claro",
    "Light": "Claro",
    "bright": "brillante",
    "Bright": "Brillante",
    "pale": "pálido",
    "Pale": "Pálido",
    # Materiales
    "iron": "hierro",
    "Iron": "Hierro",
    "steel": "acero",
    "Steel": "Acero",
    "bronze": "bronce",
    "Bronze": "Bronce",
    "copper": "cobre",
    "Copper": "Cobre",
    "gold": "oro",
    "Gold": "Oro",
    "silver": "plata",
    "Silver": "Plata",
    "mithril": "mitril",
    "Mithril": "Mitril",
    "voratun": "voratún",
    "Voratun": "Voratún",
    "stralite": "estralita",
    "Stralite": "Estralita",
    "wooden": "madera",
    "Wooden": "Madera",
    "bone": "hueso",
    "Bone": "Hueso",
    "leather": "cuero",
    "Leather": "Cuero",
    "cloth": "tela",
    "Cloth": "Tela",
    "silk": "seda",
    "Silk": "Seda",
    "wool": "lana",
    "Wool": "Lana",
    "linen": "lino",
    "Linen": "Lino",
    "elm": "olmo",
    "Elm": "Olmo",
    "oak": "roble",
    "Oak": "Roble",
    "yew": "tejo",
    "Yew": "Tejo",
    "ash": "fresno",
    "Ash": "Fresno",
    # Partes del cuerpo
    "head": "cabeza",
    "face": "cara",
    "eye": "ojo",
    "eyes": "ojos",
    "hair": "pelo",
    "beard": "barba",
    "skin": "piel",
    "hand": "mano",
    "hands": "manos",
    "arm": "brazo",
    "arms": "brazos",
    "leg": "pierna",
    "legs": "piernas",
    "foot": "pie",
    "feet": "pies",
    "finger": "dedo",
    "fingers": "dedos",
    "body": "cuerpo",
    "blood": "sangre",
    "heart": "corazón",
    "mind": "mente",
    "soul": "alma",
    # Elementos y naturaleza
    "fire": "fuego",
    "Fire": "Fuego",
    "water": "agua",
    "Water": "Agua",
    "ice": "hielo",
    "Ice": "Hielo",
    "stone": "piedra",
    "Stone": "Piedra",
    "rock": "roca",
    "Rock": "Roca",
    "sand": "arena",
    "Sand": "Arena",
    "dust": "polvo",
    "Dust": "Polvo",
    "mud": "barro",
    "Mud": "Barro",
    "clay": "arcilla",
    "Clay": "Arcilla",
    "crystal": "cristal",
    "Crystal": "Cristal",
    "grass": "hierba",
    "Grass": "Hierba",
    "tree": "árbol",
    "Tree": "Árbol",
    "flower": "flor",
    "Flower": "Flor",
    "fruit": "fruta",
    "Fruit": "Fruta",
    "plant": "planta",
    "Plant": "Planta",
    "vine": "enredadera",
    "Vine": "Enredadera",
    "moss": "musgo",
    "Moss": "Musgo",
    "root": "raíz",
    "Root": "Raíz",
    "thorn": "espina",
    "Thorns": "Espinas",
    # Lugares
    "city": "ciudad",
    "cities": "ciudades",
    "town": "pueblo",
    "village": "aldea",
    "castle": "castillo",
    "fortress": "fortaleza",
    "tower": "torre",
    "towers": "torres",
    "gate": "puerta",
    "gates": "puertas",
    "door": "puerta",
    "doors": "puertas",
    "wall": "muro",
    "walls": "muros",
    "floor": "suelo",
    "floors": "suelos",
    "room": "habitación",
    "rooms": "habitaciones",
    "hall": "salón",
    "halls": "salones",
    "cave": "cueva",
    "caves": "cuevas",
    "tunnel": "túnel",
    "tunnels": "túneles",
    "mine": "mina",
    "mines": "minas",
    "portal": "portal",
    "portals": "portales",
    "vault": "bóveda",
    "vaults": "bóvedas",
    "tomb": "tumba",
    "tombs": "tumbas",
    "shrine": "santuario",
    "shrines": "santuarios",
    "temple": "templo",
    "temples": "templos",
    "library": "biblioteca",
    "laboratory": "laboratorio",
    "prison": "prisión",
    "camp": "campamento",
    "market": "mercado",
    "inn": "posada",
    "tavern": "taberna",
    # Verbos adicionales
    "enter": "entrar",
    "enters": "entra",
    "exit": "salir",
    "exits": "sale",
    "open": "abrir",
    "opens": "abre",
    "opened": "abierto",
    "close": "cerrar",
    "closes": "cierra",
    "closed": "cerrado",
    "use": "usar",
    "uses": "usa",
    "used": "usado",
    "need": "necesitar",
    "needs": "necesita",
    "needed": "necesario",
    "take": "tomar",
    "takes": "toma",
    "took": "tomó",
    "give": "dar",
    "gives": "da",
    "gave": "dio",
    "find": "encontrar",
    "finds": "encuentra",
    "found": "encontrado",
    "seek": "buscar",
    "seeks": "busca",
    "sought": "buscado",
    "kill": "matar",
    "kills": "mata",
    "killed": "matado",
    "die": "morir",
    "dies": "muere",
    "died": "muerto",
    "slay": "aniquilar",
    "slays": "aniquila",
    "slew": "aniquiló",
    "destroy": "destruir",
    "destroys": "destruye",
    "destroyed": "destruido",
    "break": "romper",
    "breaks": "rompe",
    "broken": "roto",
    "create": "crear",
    "creates": "crea",
    "created": "creado",
    "build": "construir",
    "builds": "construye",
    "built": "construido",
    "place": "colocar",
    "places": "coloca",
    "move": "mover",
    "moves": "mueve",
    "moving": "moviendo",
    "walk": "andar",
    "walks": "anda",
    "run": "correr",
    "runs": "corre",
    "running": "corriendo",
    "jump": "saltar",
    "jumps": "salta",
    "fly": "volar",
    "flies": "vuela",
    "flying": "volando",
    "swim": "nadar",
    "swims": "nada",
    "fall": "caer",
    "falls": "cae",
    "fell": "cayó",
    "rise": "elevarse",
    "rises": "se eleva",
    "rose": "elevó",
    "sit": "sentarse",
    "sits": "se sienta",
    "lie": "yacer",
    "lies": "yace",
    "sleep": "dormir",
    "sleeps": "duerme",
    "sleeping": "durmiendo",
    "wake": "despertar",
    "wakes": "despierta",
    "eat": "comer",
    "eats": "come",
    "eating": "comiendo",
    "drink": "beber",
    "drinks": "bebe",
    "speak": "hablar",
    "speaks": "habla",
    "spoke": "habló",
    "say": "decir",
    "says": "dice",
    "said": "dijo",
    "tell": "contar",
    "tells": "cuenta",
    "told": "contó",
    "ask": "preguntar",
    "asks": "pregunta",
    "asked": "preguntó",
    "answer": "responder",
    "answers": "responde",
    "know": "saber",
    "knows": "sabe",
    "knew": "supo",
    "think": "pensar",
    "thinks": "piensa",
    "thought": "pensó",
    "feel": "sentir",
    "feels": "siente",
    "felt": "sintió",
    "see": "ver",
    "sees": "ve",
    "saw": "vio",
    "seen": "visto",
    "hear": "oír",
    "hears": "oye",
    "heard": "oyó",
    "smell": "oler",
    "smells": "huele",
    "touch": "tocar",
    "touches": "toca",
    "hold": "sostener",
    "holds": "sostiene",
    "held": "sostuvo",
    "carry": "llevar",
    "carries": "lleva",
    "wear": "vestir",
    "wears": "viste",
    "wearing": "vistiendo",
    "equip": "equipar",
    "equips": "equipa",
    "equipped": "equipado",
    "throw": "lanzar",
    "throws": "lanza",
    "threw": "lanzó",
    "catch": "atrapar",
    "catches": "atrapa",
    "push": "empujar",
    "pushes": "empuja",
    "pull": "tirar",
    "pulls": "tira",
    "lift": "levantar",
    "lifts": "levanta",
    "drop": "soltar",
    "drops": "suelta",
    "dropped": "soltado",
    "hide": "ocultar",
    "hides": "oculta",
    "hidden": "oculto",
    "show": "mostrar",
    "shows": "muestra",
    "shown": "mostrado",
    "appear": "aparecer",
    "appears": "aparece",
    "appeared": "apareció",
    "disappear": "desaparecer",
    "disappears": "desaparece",
    "live": "vivir",
    "lives": "vive",
    "lived": "vivió",
    "stay": "quedarse",
    "stays": "se queda",
    "remain": "permanecer",
    "remains": "permanece",
    "return": "volver",
    "returns": "vuelve",
    "returned": "volvió",
    "leave": "irse",
    "leaves": "se va",
    "left": "se fue",
    "follow": "seguir",
    "follows": "sigue",
    "followed": "siguió",
    "lead": "guiar",
    "leads": "guía",
    "led": "guió",
    "guard": "guardar",
    "guards": "guarda",
    "protect": "proteger",
    "protects": "protege",
    "watch": "vigilar",
    "watches": "vigila",
    "wait": "esperar",
    "waits": "espera",
    # Verbos de combate
    "fight": "luchar",
    "fighting": "luchando",
    "battle": "batallar",
    "defeat": "derrotar",
    "defeated": "derrotado",
    "conquer": "conquistar",
    "banish": "desterrar",
    "banished": "desterrado",
    "trap": "trampa",
    "traps": "trampas",
    "ambush": "emboscada",
    "retreat": "retirarse",
    "flee": "huir",
    "flees": "huye",
    "fled": "huyó",
    "surrender": "rendirse",
    # Adjetivos y atributos
    "new": "nuevo",
    "old": "viejo",
    "young": "joven",
    "dead": "muerto",
    "alive": "vivo",
    "strong": "fuerte",
    "weak": "débil",
    "fast": "rápido",
    "slow": "lento",
    "smart": "inteligente",
    "wise": "sabio",
    "brave": "valiente",
    "cruel": "cruel",
    "evil": "malvado",
    "good": "bueno",
    "kind": "amable",
    "sad": "triste",
    "happy": "feliz",
    "angry": "enfadado",
    "calm": "tranquilo",
    "wild": "salvaje",
    "savage": "salvaje",
    "huge": "enorme",
    "large": "grande",
    "big": "grande",
    "small": "pequeño",
    "tiny": "diminuto",
    "short": "corto",
    "long": "largo",
    "deep": "profundo",
    "high": "alto",
    "low": "bajo",
    "wide": "ancho",
    "thin": "delgado",
    "thick": "grueso",
    "hard": "duro",
    "soft": "blando",
    "sharp": "afilado",
    "dull": "romo",
    "heavy": "pesado",
    "light": "ligero",
    "rough": "basto",
    "smooth": "suave",
    "wet": "mojado",
    "dry": "seco",
    "clean": "limpio",
    "dirty": "sucio",
    "rich": "rico",
    "poor": "pobre",
    "free": "libre",
    "safe": "seguro",
    "dangerous": "peligroso",
    "empty": "vacío",
    "full": "lleno",
    # Tiempo
    "time": "tiempo",
    "day": "día",
    "days": "días",
    "night": "noche",
    "week": "semana",
    "month": "mes",
    "year": "año",
    "years": "años",
    "hour": "hora",
    "hours": "horas",
    "minute": "minuto",
    "minutes": "minutos",
    "second": "segundo",
    "seconds": "segundos",
    "now": "ahora",
    "then": "entonces",
    "soon": "pronto",
    "late": "tarde",
    "early": "temprano",
    "again": "otra vez",
    "always": "siempre",
    "never": "nunca",
    "once": "una vez",
    # Palabras funcionales
    "has": "ha",
    "have": "has",
    "had": "había",
    "will": "va a",
    "would": "haría",
    "can": "puede",
    "could": "podría",
    "should": "debería",
    "must": "debe",
    "may": "puede",
    "might": "quizás",
    "shall": "deberá",
    "not": "no",
    "don't": "no",
    "doesn't": "no",
    "didn't": "no",
    "won't": "no",
    "can't": "no puede",
    "isn't": "no está",
    "aren't": "no",
    "wasn't": "no estaba",
    "weren't": "no estaban",
    "its": "su",
    "it's": "es",
    "that's": "eso es",
    "there": "allí",
    "here": "aquí",
    "where": "dónde",
    "what": "qué",
    "who": "quién",
    "why": "por qué",
    "how": "cómo",
    "which": "cuál",
    "when": "cuándo",
    "much": "mucho",
    "many": "muchos",
    "few": "pocos",
    "more": "más",
    "less": "menos",
    "most": "la mayoría",
    "some": "algunos",
    "any": "cualquier",
    "each": "cada",
    "every": "cada",
    "both": "ambos",
    "either": "cualquiera",
    "neither": "ninguno",
    "other": "otro",
    "another": "otro",
    "such": "tal",
    "same": "mismo",
    "different": "diferente",
    "own": "propio",
    "very": "muy",
    "too": "demasiado",
    "only": "solo",
    "just": "solo",
    "still": "aún",
    "even": "incluso",
    "already": "ya",
    "yet": "aún",
    "about": "sobre",
    "around": "alrededor",
    "between": "entre",
    "under": "bajo",
    "over": "sobre",
    "through": "a través de",
    "across": "al otro lado",
    "behind": "detrás",
    "front": "frente",
    "beside": "junto a",
    "inside": "dentro",
    "outside": "fuera",
    "beyond": "más allá",
    "against": "contra",
    "among": "entre",
    "since": "desde",
    "until": "hasta",
    # Palabras de UI
    "you": "tú",
    "your": "tu",
    "you are": "estás",
    "you have": "tienes",
    "you can": "puedes",
    "you will": "podrás",
    "you must": "debes",
    "are you": "estás",
    "have you": "has",
    "do you": "",
    "will you": "quieres",
    "cannot": "no puedes",
    # Direcciones
    "north": "norte",
    "south": "sur",
    "east": "este",
    "west": "oeste",
    "northwest": "noroeste",
    "northeast": "noreste",
    "southwest": "suroeste",
    "southeast": "sureste",
    "up": "arriba",
    "down": "abajo",
    "left": "izquierda",
    "right": "derecha",
    "forward": "adelante",
    "backward": "atrás",
}


# =============================================================================
# REGLAS DE PLURAL
# =============================================================================
def plural_to_singular(word):
    """Convierte plurales irregulares a singular para buscar en diccionario."""
    irregulars = {
        "elves": "elf",
        "elves'": "elf",
        "dwarves": "dwarf",
        "dwarves'": "dwarf",
        "wolves": "wolf",
        "wolves'": "wolf",
        "wurms": "wurm",
        "wurms'": "wurm",
        "staves": "staff",
        "feet": "foot",
        "teeth": "tooth",
        "men": "man",
        "women": "woman",
        "children": "child",
        "lives": "life",
        "halves": "half",
    }
    # Primero ver irregulares
    lower = word.lower()
    if lower in irregulars:
        return irregulars[lower]
    # Plural regular: quitar 's' o 'es'
    if lower.endswith("es") and len(lower) > 4:
        return word[:-2]
    if lower.endswith("s") and not lower.endswith("ss") and len(lower) > 3:
        return word[:-1]
    if lower.endswith("ies") and len(lower) > 4:
        return word[:-3] + "y"
    return word


# =============================================================================
# DICCIONARIO DE FRASES COMPLETAS
# =============================================================================
PHRASES = {
    # === Logros ===
    "The Arena": "La Arena",
    "Unlocked Arena mode.": "Modo Arena desbloqueado.",
    "Arena Battler 20": "Guerrero de Arena 20",
    "Arena Battler 50": "Guerrero de Arena 50",
    "Almost Master of Arena": "Casi Maestro de la Arena",
    "Master of Arena": "Maestro de la Arena",
    "Ten at one blow": "Diez de un golpe",
    "Infinite x10": "Infinito x10",
    "Infinite x20": "Infinito x20",
    "Infinite x30": "Infinito x30",
    "Infinite x40": "Infinito x40",
    "Infinite x50": "Infinito x50",
    "Infinite x60": "Infinito x60",
    "Infinite x70": "Infinito x70",
    "Infinite x80": "Infinito x80",
    "Infinite x90": "Infinito x90",
    "Infinite x100": "Infinito x100",
    "Infinite x150": "Infinito x150",
    "Infinite x200": "Infinito x200",
    "Infinite x300": "Infinito x300",
    "Infinite x400": "Infinito x400",
    "Infinite x500": "Infinito x500",
    "Bronze Donator": "Donante de Bronce",
    "Silver Donator": "Donante de Plata",
    "Gold Donator": "Donante de Oro",
    "Stralite Donator": "Donante de Estralita",
    "Voratun Donator": "Donante de Voratún",
    "The sky is falling!": "¡El cielo se cae!",
    "Demonic Invasion": "Invasión Demoníaca",
    "Invasion from the Depths": "Invasión desde las Profundidades",
    "The Restless Dead": "Los Muertos Inquietos",
    "The Rat Lich": "El Liche Rata",
    "Bringer of Doom": "Portador de la Perdición",
    "A living one!": "¡Un ser vivo!",
    "Slimefest": "Festín de Babosas",
    "Slime killer party": "Fiesta Asesina de Babosas",
    "Mad slime dash": "Carrera Loca de Babosas",
    "Don't mind the slimy smell": "No le Hagas Caso al Olor a Baba",
    "In the company of slimes": "En Compañía de Babosas",
    "XXX the Destroyer": "XXX el Destructor",
    "Grand Master": "Gran Maestro",
    "Shasshhiy'Kaish": "Shasshhiy'Kaish",
    "Fortune's Favor": "Favor de la Fortuna",
    # === Razas ===
    "Human": "Humano",
    "Elf": "Elfo",
    "Halfling": "Mediano",
    "Dwarf": "Enano",
    "Orc": "Orco",
    "Skeleton": "Esqueleto",
    "Shalore": "Shalore",
    "Higher": "Superior",
    "Cornac": "Cornaco",
    "Thalore": "Thalore",
    "Ogre": "Ogro",
    "Draconian": "Draconiano",
    "Drem": "Drem",
    "Ghoul": "Ghul",
    "Yeek": "Yeek",
    "Krog": "Krog",
    "Doomelf": "Duendeldo",
    "Troll": "Trol",
    # === Clases ===
    "Warrior": "Guerrero",
    "Mage": "Mago",
    "Rogue": "Pícaro",
    "Archer": "Arquero",
    "Berserker": "Berserker",
    "Paladin": "Paladín",
    "Shadowblade": "Hoja Sombría",
    "Archmage": "Archimago",
    "Necromancer": "Nigromante",
    "Alchemist": "Alquimista",
    "Summoner": "Invocador",
    "Wilder": "Salvaje",
    "Sun Paladin": "Paladín Solar",
    "Anorithil": "Anoritil",
    "Corruptor": "Corruptor",
    "Reaver": "Despojador",
    "Doombringer": "Condenador",
    "Demonologist": "Demonólogo",
    "Writhing One": "Ser Retorcido",
    "Cursed": "Maldito",
    "Doomed": "Condenado",
    "Paradox Mage": "Mago de la Paradoja",
    "Temporal Warden": "Guardián Temporal",
    "Brawler": "Peleador",
    "Mind Slayer": "Psiónico",
    "Skirmisher": "Escaramuzador",
    "Marauder": "Mercenario",
    "Bulwark": "Baluarte",
    "Arcane Blade": "Hoja Arcana",
    "Adventurer": "Aventurero",
    "Annihilator": "Aniquilador",
    # === Atributos ===
    "Strength": "Fuerza",
    "Dexterity": "Destreza",
    "Constitution": "Constitución",
    "Magic": "Magia",
    "Willpower": "Voluntad",
    "Cunning": "Astucia",
    # === Tipos de recurso ===
    "Health": "Salud",
    "Mana": "Maná",
    "Stamina": "Resistencia",
    "Equilibrium": "Equilibrio",
    "Vim": "Vim",
    "Positive": "Positiva",
    "Negative": "Negativa",
    "Paradox": "Paradoja",
    "Soul": "Alma",
    "Steam": "Vapor",
    # === Keybinds ===
    "Go to next/previous level": "Ir al nivel siguiente/anterior",
    "Levelup window": "Ventana de subida de nivel",
    "Use talents": "Usar talentos",
    "Show quests": "Mostrar misiones",
    "Rest for a while": "Descansar un rato",
    "Save game": "Guardar partida",
    "Quit game": "Salir del juego",
    "Tactical display on/off": "Vista táctica act./desact.",
    "Look around": "Inspeccionar",
    "Center the view on the player": "Centrar en el jugador",
    "Toggle minimap": "Alternar minimapa",
    "Show game calendar": "Mostrar calendario",
    "Show character sheet": "Mostrar personaje",
    "Switch graphical modes": "Cambiar modo gráfico",
    "Accept action": "Aceptar",
    "Exit menu": "Salir del menú",
    "Talk to people": "Hablar",
    "Display chat log": "Ver chat",
    "Cycle chat channels": "Cambiar canal",
    "Show Lua console": "Consola Lua",
    "Debug Mode": "Modo depuración",
    # === Tipos de daño ===
    "physical": "físico",
    "physical damage": "daño físico",
    "fire": "fuego",
    "fire damage": "daño de fuego",
    "cold": "frío",
    "cold damage": "daño de frío",
    "lightning": "relámpago",
    "lightning damage": "daño de relámpago",
    "acid": "ácido",
    "acid damage": "daño de ácido",
    "nature": "naturaleza",
    "nature damage": "daño de naturaleza",
    "blight": "plaga",
    "blight damage": "daño de plaga",
    "arcane": "arcano",
    "arcane damage": "daño arcano",
    "light": "luz",
    "light damage": "daño de luz",
    "darkness": "oscuridad",
    "darkness damage": "daño de oscuridad",
    "temporal": "temporal",
    "temporal damage": "daño temporal",
    "mind": "mente",
    "mind damage": "daño mental",
    "poison": "veneno",
    "poison damage": "daño de veneno",
    # === Estados ===
    "stunned": "aturdido",
    "confused": "confundido",
    "blinded": "cegado",
    "pinned": "inmovilizado",
    "silenced": "silenciado",
    "disarmed": "desarmado",
    "dazed": "atontado",
    "slowed": "ralentizado",
    "poisoned": "envenenado",
    "burning": "en llamas",
    "frozen": "congelado",
    # === NPCs ===
    "Bill": "Bill",
    "The Withering Thing": "La Cosa Marchita",
    "Skeleton archer": "Arquero esqueleto",
    "Skeleton mage": "Mago esqueleto",
    "Skeleton warrior": "Guerrero esqueleto",
    "Armoured skeleton warrior": "Guerrero esqueleto acorazado",
    "Ghoul": "Ghul",
    "Ghast": "Ghast",
    "Ghoulking": "Rey ghul",
    "Lich": "Liche",
    "Vampire": "Vampiro",
    "Master vampire": "Vampiro maestro",
    "Orc elite": "Élite orca",
    "Orc berserker": "Berserker orco",
    "Orc mage": "Mago orco",
    "Orc necromancer": "Nigromante orco",
    "Orc fighter": "Soldado orco",
    "Orc warrior": "Guerrero orco",
    "Orc master assassin": "Maestro asesino orco",
    "Orc pyromancer": "Pirómano orco",
    "Orc cryomancer": "Criomante orco",
    "Orc corruptor": "Corruptor orco",
    "Orc summoner": "Invocador orco",
    "Orc high priest": "Sumo sacerdote orco",
    "Orc blood mage": "Mago de sangre orco",
    "Dragon": "Dragón",
    "Fire wyrm": "Dragón de fuego",
    "Cold wyrm": "Dragón de hielo",
    "Sand wyrm": "Dragón de arena",
    "Venom wyrm": "Dragón de veneno",
    "Storm wyrm": "Dragón de tormenta",
    "Great wyrm": "Gran dragón",
    # === Objetos ===
    "iron longsword": "espada larga de hierro",
    "steel longsword": "espada larga de acero",
    "iron dagger": "daga de hierro",
    "steel dagger": "daga de acero",
    "iron waraxe": "hacha de guerra de hierro",
    "steel waraxe": "hacha de guerra de acero",
    "iron greatsword": "espada bastarda de hierro",
    "steel greatsword": "espada bastarda de acero",
    "iron shield": "escudo de hierro",
    "steel shield": "escudo de acero",
    "rough leather gloves": "guantes de cuero basto",
    "pair of rough leather boots": "par de botas de cuero basto",
    "linen cloak": "capa de lino",
    "woollen robe": "túnica de lana",
    "elm magestaff": "bastón de olmo",
    "elm vilestaff": "bastón vil de olmo",
    "elm starstaff": "bastón estelar de olmo",
    "elm longbow": "arco largo de olmo",
    "rough sling": "honda basta",
    "quiver of elm arrows": "carcaj de flechas de olmo",
    "pouch of iron shots": "saco de proyectiles de hierro",
    "iron mail armour": "cota de malla de hierro",
    "iron plate armour": "armadura de placas de hierro",
    "steel mail armour": "cota de malla de acero",
    "steel plate armour": "armadura de placas de acero",
    # === Lore markers ===
    "lore": "texto histórico",
    "Lore": "Texto histórico",
    "new lore": "nuevo texto histórico",
    "tome": "tomo",
    "scroll": "pergamino",
    "note": "nota",
    "letter": "carta",
    "diary": "diario",
    "journal": "bitácora",
    "inscription": "inscripción",
    "tablet": "tablilla",
    "book": "libro",
    "story": "relato",
    "tale": "cuento",
    "legend": "leyenda",
    "myth": "mito",
    "prophecy": "profecía",
    "riddle": "acertijo",
    "poem": "poema",
    "song": "canción",
    "chronicle": "crónica",
    # === Tutorial ===
    "Welcome": "Bienvenido",
    "Introduction": "Introducción",
    "Basics": "Conceptos básicos",
    "Movement": "Movimiento",
    "Combat": "Combate",
    "Equipment": "Equipo",
    "Inventory": "Inventario",
    "Talents and Spells": "Talentos y Hechizos",
    "Level up": "Subir de nivel",
    "Quests": "Misiones",
    "Exploration": "Exploración",
    "Advanced": "Avanzado",
}


# =============================================================================
# FUNCIÓN DE TRADUCCIÓN
# =============================================================================
def translate_text(text):
    """Traduce un texto usando diccionarios y reglas."""
    if not text or text.strip() == "":
        return text

    # 1. Buscar en frases completas
    if text in PHRASES:
        return PHRASES[text]

    # 2. No traducir si tiene códigos de color (#...) o es solo eso
    if re.match(r"^#[A-Z_]+\s*#", text):
        return text

    # 3. No traducir nombres propios conocidos
    proper_names = {
        "Maj'Eyal",
        "Eyal",
        "Sher'Tul",
        "Amakthel",
        "Elandar",
        "Aeryn",
        "Celestene",
        "Linaniil",
        "Urkis",
        "Shasshhiy'Kaish",
        "Cthulhu",
        "Voratun",
        "Stralite",
        "Mithril",
        "Kerr'Bak",
        "Tannen",
    }
    if text in proper_names:
        return text

    # 4. Traducir palabra por palabra
    words = text.split(" ")
    translated_words = []
    for word in words:
        # Mantener puntuación
        stripped = word.strip(",.!?;:()[]{}'\"")
        punct_start = word[: len(word) - len(word.lstrip(",.!?;:()[]{}'\""))]
        punct_end = word[len(word.rstrip(",.!?;:()[]{}'\"")) :]

        # Inicializar trans
        trans = stripped

        # Buscar en frases completas (versión lowercase)
        if stripped.lower() in {k.lower() for k in PHRASES}:
            # Encontrar la key correcta
            for key, val in PHRASES.items():
                if key.lower() == stripped.lower():
                    trans = val
                    break
        # Buscar en diccionario EN-ES
        elif stripped.lower() in EN_ES:
            trans = EN_ES[stripped.lower()]
        elif stripped.lower().rstrip("s") in EN_ES:
            trans = EN_ES[stripped.lower().rstrip("s")]

        # Preservar capitalización
        if stripped and stripped[0].isupper() and trans:
            trans = trans[0].upper() + trans[1:] if len(trans) > 1 else trans.upper()

        translated_words.append(punct_start + trans + punct_end)

    result = " ".join(translated_words)

    # 5. Correcciones post-traducción
    # Artículos
    result = re.sub(r"\bEl (\w+) de\b", r"el \1 de", result)
    result = re.sub(r"^El ", r"el ", result)

    return result


def translate_file(fpath):
    """Traduce todas las cadenas de un archivo."""
    with open(fpath, "r", encoding="utf-8") as f:
        content = f.read()

    count = 0
    lines = content.split("\n")
    new_lines = []

    for line in lines:
        # Buscar t("original", "original|trans", "type")
        match = re.match(
            r'^(\s*)t\("((?:[^"\\]|\\.)*)"\s*,\s*"((?:[^"\\]|\\.)*)"\s*,\s*"((?:[^"\\]|\\.)*)"\s*\)',
            line,
        )
        if match:
            indent = match.group(1)
            original = match.group(2)
            current_trans = match.group(3)
            type_ = match.group(4)

            # Solo traducir si original == current (aún sin traducir)
            if original != current_trans:
                new_lines.append(line)
                continue

            # Detectar placeholders y códigos de color
            has_color = bool(re.search(r"#[A-Z_]+", original))
            has_format = bool(re.search(r"%[sd]", original))

            translation = translate_text(original)

            # Si la traducción es igual al original, forzar capitalización
            if translation == original or not translation:
                translation = original
            else:
                count += 1

            safe_translation = translation.replace('"', '\\"')
            new_line = f'{indent}t("{original}", "{safe_translation}", "{type_}")'
            new_lines.append(new_line)
        else:
            new_lines.append(line)

    new_content = "\n".join(new_lines)
    with open(fpath, "w", encoding="utf-8") as f:
        f.write(new_content)

    return count


def main():
    print("=" * 60)
    print("  TRADUCCIÓN MASIVA COMPLETA — ToME4-es")
    print("=" * 60)

    files = sorted(TRANS_DIR.glob("*.lua"))
    total = 0

    for fpath in files:
        if fpath.name in (
            "_t_append.lua",
            "_not_merged.lua",
            "i18n.log",
            "copy_files.py",
        ):
            continue

        print(f"\n  📄 {fpath.name}...", end=" ")
        count = translate_file(str(fpath))
        print(f"✓ {count} cadenas traducidas")
        total += count

    print(f"\n{'=' * 60}")
    print(f"  TOTAL: {total} cadenas traducidas")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
