#!/usr/bin/env python3
"""
Traduce mod-boot.lua (284 cadenas).
Menús principales, razas, clases, tipos de daño, grids, NPCs iniciales.

Uso: python3 scripts/translate_modboot.py
"""

import re
from pathlib import Path

TRANS_DIR = Path(__file__).parent.parent / "translations" / "es"
BOOT_FILE = TRANS_DIR / "mod-boot.lua"

DICT = {
    # === Birth descriptors (razas, clases) ===
    "None": "Ninguno",
    "Tutorial": "Tutorial",
    "Normal": "Normal",
    "Nightmare": "Pesadilla",
    "Insane": "Insano",
    "Madness": "Locura",
    "Exploration": "Exploración",
    "Roguelike": "Roguelike",
    "Adventure": "Aventura",
    "base": "base",
    "Destroyer": "Destructor",
    "Special": "Especial",
    "Facial features": "Rasgos faciales",
    "Tatoos": "Tatuajes",
    "Beards": "Barbas",
    "Hairstyles": "Peinados",
    "Hair": "Pelo",
    "Beard": "Barba",
    "Skin": "Piel",
    "Skin color": "Color de piel",
    "Hair color": "Color de pelo",
    "Eye color": "Color de ojos",
    # === Damage types ===
    "Acid": "Ácido",
    "Blight": "Plaga",
    "Cold": "Frío",
    "Darkness": "Oscuridad",
    "Fire": "Fuego",
    "Light": "Luz",
    "Lightning": "Relámpago",
    "Mind": "Mente",
    "Nature": "Naturaleza",
    "Physical": "Físico",
    "Temporal": "Temporal",
    "Arcane": "Arcano",
    "Burning": "Quemadura",
    "Bleed": "Sangrado",
    "Poison": "Veneno",
    "Disease": "Enfermedad",
    "Cut": "Corte",
    "Crushing": "Aplastamiento",
    "Stunning": "Aturdimiento",
    "Knockback": "Derribo",
    "Acid-maniac": "Ácido-maníaco",
    "Kill!": "¡Matar!",
    "Acid Spray": "Rociada ácida",
    "Burning from acid": "Quemadura por ácido",
    "+Acid": "+Ácido",
    "-Acid": "-Ácido",
    # === Grids (tiles del mapa) ===
    "floor": "suelo",
    "grass": "hierba",
    "wall": "muro",
    "tree": "árbol",
    "flower": "flor",
    "water": "agua",
    "deep water": "agua profunda",
    "shallow water": "agua superficial",
    "underground": "subterráneo",
    "crystals": "cristales",
    "stone": "piedra",
    "rock": "roca",
    "sand": "arena",
    "lava": "lava",
    "ice": "hielo",
    "snow": "nieve",
    "mud": "barro",
    "grassland": "pradera",
    "forest": "bosque",
    "mountain": "montaña",
    "hill": "colina",
    "river": "río",
    "lake": "lago",
    "ocean": "océano",
    "road": "camino",
    "bridge": "puente",
    "door": "puerta",
    "open door": "puerta abierta",
    "closed door": "puerta cerrada",
    "secret door": "puerta secreta",
    "stair": "escalera",
    "stairs": "escaleras",
    "stair up": "escaleras arriba",
    "stair down": "escaleras abajo",
    "trap": "trampa",
    "chest": "cofre",
    "altar": "altar",
    "fountain": "fuente",
    "statue": "estatua",
    # === NPCs ===
    "animal": "animal",
    "canine": "canino",
    "wolf": "lobo",
    "great wolf": "lobo grande",
    "warg": "huargo",
    "bear": "oso",
    "skeleton": "esqueleto",
    "skeletal": "esquelético",
    "armoured skeleton": "esqueleto acorazado",
    "skeleton warrior": "guerrero esqueleto",
    "skeleton archer": "arquero esqueleto",
    "skeleton mage": "mago esqueleto",
    "skeleton master": "maestro esqueleto",
    "skeleton berserker": "berserker esqueleto",
    "skeleton elite": "élite esqueleto",
    "lich": "liche",
    "lich skeleton": "liche esqueleto",
    "troll": "trol",
    "mountain troll": "trol de montaña",
    "cave troll": "trol de cueva",
    "troll guard": "guardia trol",
    "stone troll": "trol de piedra",
    # === Atributos (stats) ===
    "Strength": "Fuerza",
    "Dexterity": "Destreza",
    "Constitution": "Constitución",
    "Magic": "Magia",
    "Willpower": "Voluntad",
    "Cunning": "Astucia",
    "str": "Fue",
    "dex": "Des",
    "con": "Con",
    "mag": "Mag",
    "wil": "Vol",
    "cun": "Ast",
    # === Habilidades (talents) ===
    "Combat": "Combate",
    "Combat training": "Entrenamiento de combate",
    "Survival": "Supervivencia",
    "Cunning / Survival": "Astucia / Supervivencia",
    "Technique / Combat training": "Técnica / Entrenamiento de combate",
    "Technique / Combat techniques": "Técnica / Técnicas de combate",
    "technique": "técnica",
    "spell": "hechizo",
    "Spell": "Hechizo",
    "cunning": "astucia",
    "wild gift": "don salvaje",
    "Wild gift": "Don salvaje",
    "psionic": "psiónico",
    "Psionic": "Psiónico",
    "race": "raza",
    "Race": "Raza",
    "undead": "no-muerto",
    "Undead": "No-muerto",
    # === Menú principal ===
    "Main Menu": "Menú principal",
    "New Game": "Nueva partida",
    "Load Game": "Cargar partida",
    "Save Game": "Guardar partida",
    "Options": "Opciones",
    "Addons": "Addons",
    "Credits": "Créditos",
    "Quit": "Salir",
    "Back": "Atrás",
    "Continue": "Continuar",
    "Play": "Jugar",
    "Start": "Empezar",
    "Delete": "Eliminar",
    "Cancel": "Cancelar",
    "Yes": "Sí",
    "No": "No",
    # === Pantalla de carga ===
    "Loading...": "Cargando...",
    "Please wait...": "Espera por favor...",
    "Initializing...": "Inicializando...",
    "Loading addons...": "Cargando addons...",
    "Loading module...": "Cargando módulo...",
    "Generating world...": "Generando mundo...",
    "Loading player data...": "Cargando datos del jugador...",
    # === Addons ===
    "Configure Addons": "Configurar addons",
    "Addon": "Addon",
    "Addon Version": "Versión del addon",
    "Enabled": "Activado",
    "Disabled": "Desactivado",
    "Active": "Activo",
    "Inactive": "Inactivo",
    "Requires: %s": "Requiere: %s",
    "Incompatible with: %s": "Incompatible con: %s",
    "No addons installed.": "No hay addons instalados.",
    "Click to configure": "Click para configurar",
    # === Perfil online ===
    "Profile": "Perfil",
    "Login": "Iniciar sesión",
    "Register": "Registrarse",
    "Logout": "Cerrar sesión",
    "Username": "Usuario",
    "Password": "Contraseña",
    "Email": "Email",
    "Create Account": "Crear cuenta",
    "Forgot password?": "¿Olvidaste tu contraseña?",
    "Online profile": "Perfil online",
    "Offline mode": "Modo offline",
    "Connecting...": "Conectando...",
    "Connected": "Conectado",
    "Disconnected": "Desconectado",
    # === Altas puntuaciones ===
    "High Scores": "Altas puntuaciones",
    "Rank": "Rango",
    "Name": "Nombre",
    "Level": "Nivel",
    "Class": "Clase",
    "Score": "Puntuación",
    "Died on": "Muerto en",
    "Killed by": "Matado por",
    "Duration": "Duración",
    "Campaign": "Campaña",
    # === Zone ===
    "dungeon": "mazmorra",
    "Dungeon": "Mazmorra",
    "wilderness": "jungla",
    "Wilderness": "Jungla",
    "town": "ciudad",
    "Town": "Ciudad",
    # === Timed effects ===
    "regeneration": "regeneración",
    "Regeneration": "Regeneración",
    "healing": "curación",
    "Healing": "Curación",
    "poison": "veneno",
    "stun": "aturdimiento",
    "Stun": "Aturdimiento",
    "confusion": "confusión",
    "Confusion": "Confusión",
    "blind": "ceguera",
    "Blind": "Ceguera",
    "silence": "silencio",
    "Silence": "Silencio",
    "slow": "ralentización",
    "Slow": "Ralentización",
    "haste": "celeridad",
    "Haste": "Celeridad",
    "shield": "escudo",
    "Shield": "Escudo",
    "freeze": "congelación",
    "Freeze": "Congelación",
    "burn": "quemadura",
    "Burn": "Quemadura",
    "sleep": "sueño",
    "Sleep": "Sueño",
    "fear": "miedo",
    "Fear": "Miedo",
    # === Diálogos del juego ===
    "New Game - %s": "Nueva partida - %s",
    "Load Game - %s": "Cargar partida - %s",
    "Are you sure you want to quit?": "¿Seguro que quieres salir?",
    "Are you sure you want to delete this character?": "¿Seguro que quieres borrar este personaje?",
    "Game saved.": "Partida guardada.",
    "Saving...": "Guardando...",
    "Load failed!": "¡Carga fallida!",
    "Save failed!": "¡Guardado fallido!",
    "Version: %s": "Versión: %s",
    "Module version: %s": "Versión del módulo: %s",
    "Game version: %s": "Versión del juego: %s",
    # === NPC descriptions ===
    "Lean, mean, and shaggy, it stares at you with hungry eyes.": "Magro, hirsuto y fiero, te mira con ojos hambrientos.",
    "white wolf": "lobo blanco",
    "A large and muscled wolf from the northern wastes. Its breath is cold ": "Un lobo grande y musculoso de los páramos del norte. Su aliento es frío ",
    "It is a large wolf with eyes full of cunning.": "Es un lobo grande con ojos llenos de astucia.",
    "fox": "zorro",
    "The quick brown fox jumps over the lazy dog.": "El rápido zorro marrón salta sobre el perro perezoso.",
    "degenerated skeleton warrior": "guerrero esqueleto degenerado",
    "armoured skeleton warrior": "guerrero esqueleto acorazado",
    "giant": "gigante",
    "forest troll": "trol del bosque",
    "Green-skinned and ugly, this massive humanoid glares at you, clenching": "De piel verde y aspecto horrible, este enorme humanoide te mira fijamente",
    "A giant troll with scabrous black skin. With a shudder, you notice the": "Un trol gigante de piel negra y escamosa. Con un escalofrío, notas los",
    "This huge troll wields a massive spear and has a disturbingly intellig": "Este enorme trol empuña una lanza masiva y tiene una inteligencia",
    "A large and athletic troll with an extremely tough and warty hide.": "Un trol grande y atlético de piel extremadamente dura y verrugosa.",
    "mountain troll thunderer": "trol montañés atronador",
    # === Talentos ===
    "misc": "varios",
    "Kick": "Patada",
    "Manathrust": "Empuje de maná",
    "Flame": "Llama",
    "Fireflash": "Destello ígneo",
    "Sunshield": "Escudo solar",
    "Flameshock": "Descarga ígnea",
    "Forest": "Bosque",
    # === UI ===
    "Welcome to T-Engine and the Tales of Maj'Eyal": "Bienvenido a T-Engine y Tales of Maj'Eyal",
    "Upgrade to 1.0.5": "Actualizar a 1.0.5",
    "Safe Mode": "Modo seguro",
    "Message": "Mensaje",
    "Duplicate Addon": "Addon duplicado",
    "Really exit T-Engine/ToME?": "¿Salir de T-Engine/ToME?",
    "Logging in...": "Iniciando sesión...",
    "Profile logged in!": "¡Perfil conectado!",
    "Your online profile is now active. Have fun!": "Tu perfil online está activo. ¡Diviértete!",
    "Login failed!": "¡Error al iniciar sesión!",
    "Check your login and password or try again in in a few moments.": "Comprueba tu usuario y contraseña o inténtalo de nuevo en unos momentos.",
    "Registering...": "Registrando...",
    "Registering on https://te4.org/, please wait...": "Registrando en https://te4.org/, espera...",
    "Logged in!": "¡Sesión iniciada!",
    "Profile created!": "¡Perfil creado!",
    "Profile creation failed!": "¡Error al crear perfil!",
    "Try again in in a few moments, or try online at https://te4.org/": "Inténtalo de nuevo en unos momentos, o prueba online en https://te4.org/",
    "Creation failed: %s (you may also register on https://te4.org/)": "Error al crear: %s (también puedes registrarte en https://te4.org/)",
    "%s available": "%s disponible",
    "LEVEL UP!": "¡SUBIR DE NIVEL!",
    "You can get new addons at #LIGHT_BLUE##{underline}#Te4.org Addons#{normal}#": "Puedes conseguir nuevos addons en #LIGHT_BLUE##{underline}#Te4.org Addons#{normal}#",
    " and #LIGHT_BLUE##{underline}#Te4.org DLCs#{normal}#": " y #LIGHT_BLUE##{underline}#Te4.org DLCs#{normal}#",
    "You can get new addons on #LIGHT_BLUE##{underline}#Steam Workshop#{normal}#": "Puedes conseguir addons en #LIGHT_BLUE##{underline}#Steam Workshop#{normal}#",
    ", #LIGHT_BLUE##{underline}#Te4.org Addons#{normal}#": ", #LIGHT_BLUE##{underline}#Te4.org Addons#{normal}#",
    "Show incompatible": "Mostrar incompatibles",
    "Game Module": "Módulo del juego",
    "Version": "Versión",
    "#GREY#Developer tool": "#GREY#Herramienta de desarrollo",
    "#LIGHT_RED#Donator Status: Disabled": "#LIGHT_RED#Estado de donante: Desactivado",
    # === Varios ===
    "Age Check": "Verificación de edad",
    "All updates installed, the game will now restart": "Todas las actualizaciones instaladas, el juego se reiniciará",
    "All your game modules are up to date.": "Todos tus módulos están actualizados.",
    "Auto-update on start": "Actualizar automáticamente al inicio",
    "Checking for updates...": "Buscando actualizaciones...",
    "Update available": "Actualización disponible",
    "Downloading...": "Descargando...",
    "Update complete": "Actualización completa",
    "Restart now": "Reiniciar ahora",
    "Restart later": "Reiniciar después",
    "Component": "Componente",
    "Community Managers": "Community Managers",
    "Code Heroes": "Héroes del código",
    "Chinese Translation Lead": "Líder de traducción al chino",
    "Chinese Translators": "Traductores al chino",
    "Spanish Translation": "Traducción al español",
    "Contributors": "Contribuidores",
    "Testing": "Pruebas",
    "Thanks": "Agradecimientos",
    "#LIGHT_GREEN#Manual: Active": "#LIGHT_GREEN#Manual: Activo",
    "#LIGHT_RED#Manual: Disabled": "#LIGHT_RED#Manual: Desactivado",
    "#LIGHT_GREEN#Auto: Active": "#LIGHT_GREEN#Auto: Activo",
    "#LIGHT_RED#Auto: Incompatible": "#LIGHT_RED#Auto: Incompatible",
    "Game Version": "Versión del juego",
    "Original game version not found": "Versión original no encontrada",
    "Run with newer version": "Ejecutar con versión reciente",
    "Developer Mode": "Modo desarrollador",
    "Load anyway": "Cargar de todas formas",
    "Delete savefile": "Eliminar partida",
    "Really delete #{bold}##GOLD#%s#WHITE##{normal}#": "¿Eliminar #{bold}##GOLD#%s#WHITE##{normal}#?",
    "Old game data": "Datos antiguos",
    "No data available for this game version.": "No hay datos para esta versión.",
    "Downloading old game data: #LIGHT_GREEN#": "Descargando datos antiguos: #LIGHT_GREEN#",
    "Old game data for %s correctly installed. You can now play.": "Datos antiguos para %s instalados. Ya puedes jugar.",
    "Failed to install.": "Error al instalar.",
    "Game Options": "Opciones del juego",
    "Show older versions": "Mostrar versiones antiguas",
    "Ignore unloadable addons": "Ignorar addons no cargables",
    "Updating addon: #LIGHT_GREEN#%s": "Actualizando addon: #LIGHT_GREEN#%s",
    # === Efectos ===
    "#Target# is covered in acid!": "¡#Target# está cubierto de ácido!",
    "#Target# is free from the acid.": "#Target# está libre del ácido.",
    "#00ff00#Talent %s is ready to use.": "#00ff00#Talento %s listo para usar.",
    # === Créditos ===
    "Project Lead": "Director del proyecto",
    "Lead Coder": "Programador principal",
    "World Builders": "Constructores del mundo",
    "Graphic Artists": "Artistas gráficos",
    "Expert Shaders Design": "Diseño experto de shaders",
    "Soundtracks": "Banda sonora",
    "Sound Designer": "Diseñador de sonido",
    "Lore Creation and Writing": "Creación y escritura del lore",
    "Text Editors": "Editores de texto",
    "Korean Translation": "Traducción al coreano",
    "Japanese Translation": "Traducción al japonés",
    "The Community": "La comunidad",
    # === Pantalla de inicio ===
    "Welcome to Tales of Maj'Eyal": "Bienvenido a Tales of Maj'Eyal",
    "Register now!": "¡Regístrate ahora!",
    "Login existing account": "Iniciar sesión existente",
    "Maybe later": "Quizás más tarde",
    "#RED#Disable all online features": "#RED#Desactivar funciones online",
    "Disable all connectivity": "Desactivar toda conectividad",
    "#RED#Disable all!": "#RED#¡Desactivar todo!",
    "  Play!  ": "  ¡Jugar!  ",
    # === Perfil y login (adicionales) ===
    "Do you want to log out?": "¿Quieres cerrar sesión?",
    "Log out": "Cerrar sesión",
    "Logging in your account, please wait...": "Iniciando sesión, espera...",
    "Login with Steam": "Iniciar sesión con Steam",
    "Login...": "Iniciando sesión...",
    "Online profile ": "Perfil online ",
    "You are logged in": "Has iniciado sesión",
    "Player Profile": "Perfil del jugador",
    "Privacy Policy (opens in browser)": "Política de privacidad (se abre en el navegador)",
    "Steam User Account": "Cuenta de usuario Steam",
    "Steam client not found.": "Cliente Steam no encontrado.",
    "Nothing to update": "Nada que actualizar",
    "Update": "Actualizar",
    "Reboot": "Reiniciar",
    "Update all game modules": "Actualizar todos los módulos",
    "Show all versions": "Mostrar todas las versiones",
    "View High Scores": "Ver altas puntuaciones",
    "World": "Mundo",
    "Error": "Error",
    "Error!": "¡Error!",
    "Exit": "Salir",
    "Create": "Crear",
    "Email: ": "Email: ",
    "Password: ": "Contraseña: ",
    "Password again: ": "Contraseña de nuevo: ",
    "Password mismatch!": "¡Las contraseñas no coinciden!",
    "Username: ": "Usuario: ",
    "Username or Email already taken, please select an other one.": "Usuario o Email ya en uso, elige otro.",
    "Your email does not look right.": "Tu email no parece correcto.",
    "Your email seems invalid": "Tu email parece inválido",
    "Your password is too short": "Tu contraseña es demasiado corta",
    "Your username is too short": "Tu usuario es demasiado corto",
    "You at least 16 years old, or have parental authorization to play the ": "Tienes al menos 16 años, o autorización parental para jugar ",
    "You need to be 16 years old or more or to have parental authorization ": "Necesitas tener 16 años o más, o autorización parental ",
    # === Diálogo de carga ===
    "Overwrite character?": "¿Sobrescribir personaje?",
    "There is already a character with this name, do you want to overwrite ": "Ya existe un personaje con ese nombre, ¿quieres sobrescribirlo?",
    "Enter your character's name": "Introduce el nombre de tu personaje",
    "Engine: #{italic}##LIGHT_BLUE#": "Motor: #{italic}##LIGHT_BLUE#",
    "Game: #{bold}##GOLD#": "Juego: #{bold}##GOLD#",
    "This game is not compatible with your version of T-Engine, you can sti": "Este juego no es compatible con tu versión de T-Engine, puedes ",
    "You can simply grab an older version of the game from where you downlo": "Puedes descargar una versión anterior desde donde descargaste ",
    "Accept to receive #{bold}#very infrequent#{normal}# (a few per year) m": "Acepto recibir #{bold}#poco frecuentes#{normal}# (unas pocas al año)",
    "Others": "Otros",
    # === Descargas ===
    "Downloading: ": "Descargando: ",
    "Disable animated background": "Desactivar fondo animado",
    # === NPC descriptions restantes ===
    "Green-skinned and ugly, this massive humanoid glares at you, clenching": "De piel verde y horrible, este enorme humanoide te mira fijamente",
    "A giant troll with scabrous black skin. With a shudder, you notice the": "Un trol gigante de piel escamosa. Con un escalofrío notas los",
    # === Títulos ===
    "Tales of Maj'Eyal Main Menu": "Menú principal de Tales of Maj'Eyal",
    # === Últimas cadenas ===
    "A large and muscled wolf from the northern wastes. Its breath is cold and icy and its fur ": "Un lobo grande y musculoso de los páramos del norte. Su aliento es frío y helado y su pelaje ",
    "Green-skinned and ugly, this massive humanoid glares at you, clenching wart-covered green ": "De piel verde y horrible, este enorme humanoide te mira fijamente, apretando sus puños ",
    "A giant troll with scabrous black skin. With a shudder, you notice the belt of dwarf skull": "Un trol gigante de piel negra y escamosa. Con un escalofrío, notas el cinturón de cráneos",
    "This huge troll wields a massive spear and has a disturbingly intelligent look in its pigg": "Este enorme trol empuña una lanza masiva y tiene una mirada inquietantemente inteligente",
    "You can simply grab an older version of the game from where you downloaded it.": "Puedes descargar una versión anterior desde donde descargaste el juego.",
    "#LIGHT_RED#WARNING: #LAST#Loading a savefile while in developer mode will permanently inva": "#LIGHT_RED#AVISO: #LAST#Cargar una partida en modo desarrollador invalidará permanentemente ",
    "#{bold}##B9E100#T-Engine4 version: %d.%d.%d": "#{bold}##B9E100#Versión T-Engine4: %d.%d.%d",
    "#LIGHT_GREEN#Installed": "#LIGHT_GREEN#Instalado",
    "#YELLOW#Not installed - Click to download / purchase": "#YELLOW#No instalado - Click para descargar/comprar",
    "#GOLD#Online Profile": "#GOLD#Perfil online",
    "#GOLD#Online Profile#WHITE#": "#GOLD#Perfil online#WHITE#",
    "#LIGHT_BLUE##{underline}#%s#LAST##{normal}#": "#LIGHT_BLUE##{underline}#%s#LAST##{normal}#",
    "#LIGHT_BLUE##{underline}#Logout": "#LIGHT_BLUE##{underline}#Cerrar sesión",
    "There is already a character with this name, do you want to overwrite it?": "Ya existe un personaje con ese nombre, ¿quieres sobrescribirlo?",
    "This game is not compatible with your version of T-Engine, you can still try it but it mig": "Este juego no es compatible con tu versión de T-Engine, puedes probarlo pero podría ",
    "Accept to receive #{bold}#very infrequent#{normal}# (a few per year) mails about important": "Acepto recibir #{bold}#poco frecuentes#{normal}# (unas pocas al año) sobre importantes ",
    "You at least 16 years old, or have parental authorization to play the game.": "Tienes al menos 16 años, o autorización parental para jugar.",
    "You need to be 16 years old or more or to have parental authorization to play this game.": "Necesitas 16 años o más, o autorización parental para jugar.",
}


def translate_boot():
    with open(BOOT_FILE, "r", encoding="utf-8") as f:
        content = f.read()

    count = 0
    lines = content.split("\n")
    new_lines = []

    for line in lines:
        m = re.match(
            r'^(\s*)t\("((?:[^"\\]|\\.)*)"\s*,\s*"((?:[^"\\]|\\.)*)"\s*,\s*"((?:[^"\\]|\\.)*)"\s*\)',
            line,
        )
        if m:
            indent = m.group(1)
            original = m.group(2)
            current = m.group(3)
            type_ = m.group(4)

            if original != current:
                new_lines.append(line)
                continue

            if original in DICT:
                trans = DICT[original]
                safe = trans.replace('"', '\\"')
                new_lines.append(f'{indent}t("{original}", "{safe}", "{type_}")')
                count += 1
            else:
                new_lines.append(line)
        else:
            new_lines.append(line)

    with open(BOOT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(new_lines))

    return count


def main():
    print("=" * 60)
    print("  TRADUCIENDO MOD-BOOT.LUA")
    print("=" * 60)

    count = translate_boot()
    print(f"\n  ✅ {count} cadenas traducidas")

    with open(BOOT_FILE) as f:
        content = f.read()
    untranslated = 0
    for line in content.split("\n"):
        m = re.match(r't\("([^"]*)",\s*"([^"]*)",', line)
        if m and m.group(1) == m.group(2):
            untranslated += 1
    print(f"  📊 Quedan {untranslated} sin traducir")
    print()


if __name__ == "__main__":
    main()
