"""
Diccionario de términos del juego para ToME4-es.
Controla qué se traduce automáticamente y cómo.
"""

NO_TRANSLATE = {
    # Nombres de artefactos únicos
    "Acera",
    "Aetherwalk",
    "Anmalice",
    "Bloomsoul",
    "Blood-Edge",
    "Blood-Letter",
    "Blightstopper",
    "Butcher",
    "Cinderfeet",
    "Colaryem",
    "Corpathus",
    "Corpsebow",
    "Eclipse",
    "Exiler",
    "Firewalker",
    "Flamewrought",
    "Latafayn",
    "Lightbringer",
    "Linaniil",
    "Malediction",
    "Mankini",
    "Mercy",
    "Mnemonic",
    "Morrigor",
    "Nightsong",
    "Obliterator",
    "Radiance",
    "Shieldsmaiden",
    "Skullcleaver",
    "Sludgegrip",
    "Spellblade",
    "Spellcrusher",
    "Spelldrinker",
    "Stormfront",
    "Stormlash",
    "Summertide",
    "Swordbreaker",
    "Tarrasca",
    "Thunderfall",
    "Titanic",
    "Umbraphage",
    "Vilespawn",
    "Vox",
    "Wintertide",
    "Witch-Bane",
    "Wyrmbreath",
    "Rolf",
    "Weisman",
    # Nombres propios del juego
    "Maj'Eyal",
    "Eyal",
    "Sher'Tul",
    "ToME",
    "ToME4",
    "Amakthel",
    "Elandar",
    "Aeryn",
    "Urkis",
    "Voratun",
    "Stralite",
    "Mithril",
    # Zonas principales
    "Trollmire",
    "Kor'Pul",
    "Daikara",
    "Dreadfell",
    "Angolwen",
    "Zigur",
    "Derth",
    "Elvala",
    "Last Hope",
    "Iron Throne",
    "High Peak",
    "Lake of Nur",
    "Charred Scar",
}

FORCED_TERMS = {
    # Razas
    "Human": "Humano",
    "Elf": "Elfo",
    "Dwarf": "Enano",
    "Halfling": "Mediano",
    "Ogre": "Ogro",
    "Troll": "Trol",
    "Orc": "Orco",
    "Skeleton": "Esqueleto",
    "Ghoul": "Ghul",
    "Yeek": "Yeek",
    "Shalore": "Shalore",
    "Higher": "Superior",
    "Cornac": "Cornaco",
    "Thalore": "Thalore",
    "Drem": "Drem",
    "Krog": "Krog",
    "Doomelf": "Duendeldo",
    "Draconian": "Draconiano",
    # Clases
    "Warrior": "Guerrero",
    "Mage": "Mago",
    "Rogue": "Pícaro",
    "Archer": "Arquero",
    "Berserker": "Berserker",
    "Paladin": "Paladín",
    "Shadowblade": "Hoja Sombría",
    "Archmage": "Archimago",
    "Necromancer": "Nigromante",
    "Alchemist": "Alquimista",
    "Summoner": "Invocador",
    "Wilder": "Salvaje",
    "Sun Paladin": "Paladín Solar",
    "Anorithil": "Anoritil",
    "Corruptor": "Corruptor",
    "Reaver": "Despojador",
    "Doombringer": "Condenador",
    "Demonologist": "Demonólogo",
    "Writhing One": "Ser Retorcido",
    "Cursed": "Maldito",
    "Doomed": "Condenado",
    "Paradox Mage": "Mago de la Paradoja",
    "Temporal Warden": "Guardián Temporal",
    "Brawler": "Peleador",
    "Mind Slayer": "Psiónico",
    "Skirmisher": "Escaramuzador",
    "Marauder": "Mercenario",
    "Bulwark": "Baluarte",
    "Arcane Blade": "Hoja Arcana",
    "Adventurer": "Aventurero",
    "Annihilator": "Aniquilador",
    # Atributos
    "Strength": "Fuerza",
    "Dexterity": "Destreza",
    "Constitution": "Constitución",
    "Magic": "Magia",
    "Willpower": "Voluntad",
    "Cunning": "Astucia",
    # Talentos conocidos
    "Flame": "Llama",
    "Freeze": "Congelar",
    "Lightning": "Relámpago",
    "Manathrust": "Empuje de Maná",
    "Teleport": "Teletransporte",
    "Phase Door": "Puerta Dimensional",
    "Illuminate": "Iluminar",
    "Shatter": "Hacer Añicos",
    "Meteor": "Meteoro",
    # Tipos de daño
    "physical": "físico",
    "fire": "fuego",
    "cold": "frío",
    "lightning": "relámpago",
    "acid": "ácido",
    "nature": "naturaleza",
    "blight": "plaga",
    "arcane": "arcano",
    "light": "luz",
    "darkness": "oscuridad",
    "temporal": "temporal",
    "mind": "mente",
    "poison": "veneno",
    # Diálogos / UI
    "Hrmph.": "Hrmpf.",
    "Ok...": "Vale...",
    "error!": "¡error!",
    "Escort": "Escolta",
    "Warp": "Distorsión",
    "Temporal": "Temporal",
    "Armour Hardiness": "Fortaleza de Armadura",
    "Armour": "Armadura",
    "Primed Trigger": "Gatillo Preparado",
    "Normal Trigger": "Gatillo Normal",
    # Keywords de objetos (egos)
    "arcing": "arqueante",
    "vile": "vil",
    "elemental": "elemental",
    "tundral": "tundral",
    "manaburning": "quemamaná",
    "flaming": "llameante",
    "icy": "helado",
    "frozen": "congelado",
    "scorching": "abrasador",
    "shimmering": "brillante",
    "crackling": "crepitante",
    "caustic": "cáustico",
    "blighted": "maldito",
    "venomous": "venenoso",
    "verdant": "verdeante",
    "thorny": "espinoso",
    "wintry": "invernal",
    "infernal": "infernal",
    "ethereal": "etéreo",
    "brutal": "brutal",
    "cruel": "cruel",
    "swiftstrike": "golpeveloz",
    "mossy": "musgoso",
    "slimy": "baboso",
    "multihued": "multicolor",
    "windwalling": "muroviento",
    "shearing": "cortante",
    "piercing": "perforante",
    "sensing": "sensorial",
    "radiance": "resplandor",
    "dispeller": "disipador",
    "spiritwalk": "caminante espiritual",
    "sunseal": "sellosolar",
    "stormbringer": "portatormentas",
    "magehunters": "cazamagos",
    "voidstriker": "golpevacío",
    "dreamer": "soñador",
    "solipsist": "solipsista",
    "psionic": "psiónico",
    "psion": "psión",
    "timebroken": "tiempoquebrado",
    "bloodhexed": "sangrehechizada",
    "mindblast": "explosiónmental",
    "mindcage": "jaulamental",
    "mindweaver": "tejedoramental",
    "mindcraft": "artemental",
    "learwalker": "caminante del saber",
    "starseeker": "buscador de estrellas",
    "stargazer": "observador de estrellas",
    "starseer": "vidente de estrellas",
    "starseers": "videntes de estrellas",
    "voidstriker": "golpevacío",
    "warmaker": "hacedor de guerra",
    "warbringer": "portaguerra",
    "watchleader": "líder de guardia",
    "battlemaster": "maestro de batalla",
    "skylord": "señor del cielo",
    "swashbuckler": "espadachín",
    "gladiator": "gladiador",
    "champion": "campeón",
    "ravager": "devastador",
    "titan": "titán",
    "warlord": "señor de la guerra",
    "marshal": "mariscal",
    "marauder": "mercenario",
    "brawler": "peleador",
    "ranger": "explorador",
    "archer": "arquero",
    "rogue": "pícaro",
    "conjurer": "conjurador",
    "alchemist": "alquimista",
    "magewarrior": "magoguerrero",
    "magelord": "señor de la magia",
    "magery": "magia",
    # Subtipos de armas
    "battleaxe": "hacha de batalla",
    "longbow": "arco largo",
    "whip": "látigo",
    "mindstar": "estrellamental",
    "torque": "torque",
    "totem": "tótem",
    "staff": "bastón",
    "dagger": "daga",
    "greatsword": "espada enorme",
    "greatmaul": "mazo enorme",
    "waraxe": "hacha de guerra",
    "mace": "maza",
    "sword": "espada",
    "sling": "honda",
    "shot": "munición",
    "arrow": "flecha",
    "quiver": "carcaj",
    # Materiales
    "cashmere": "cachemira",
    "e.silk": "seda élfica",
    "e.wood": "madera élfica",
    "orichalcum": "oricalco",
    "voratun": "voratún",
    "stralite": "stralita",
    "mithril": "mitril",
    "dragonbone": "hueso de dragón",
    "elven-wood": "madera élfica",
    "yew": "tejo",
    "ash": "fresno",
    "elm": "olmo",
    "boned": "óseo",
    "iron": "hierro",
    "steel": "acero",
    "hardened": "endurecido",
    # Gemas
    "agate": "ágata",
    "aquamarine": "aguamarina",
    "citrine": "citrino",
    "garnet": "granate",
    "jade": "jade",
    "moonstone": "piedra lunar",
    "onyx": "ónix",
    "spinel": "espinela",
    "zircon": "circón",
    "amethyst": "amatista",
    "diamond": "diamante",
    "emerald": "esmeralda",
    "pearl": "perla",
    "quartz": "cuarzo",
    "ruby": "rubí",
    "sapphire": "zafiro",
    "topaz": "topacio",
    "opal": "ópalo",
    # Abreviaturas de stats
    "con": "con",
    "dex": "des",
    "def": "def",
    "mag": "mag",
    "wil": "vol",
    "cun": "ast",
    "str": "fuer",
    "apr": "per",
    "prot": "prot",
    "rdef": "rdef",
    "regen": "regen",
    "rejuv": "rejuve",
    "lite": "lum",
    "invigor.": "vigor.",
    "fortif.": "fortif.",
    "implac.": "implac.",
    "serend.": "serend.",
    # Stats completas
    "constitution": "constitución",
    "dexterity": "destreza",
    "cunning": "astucia",
    "willpower": "voluntad",
    "magic": "magia",
    "strength": "fuerza",
    "perception": "percepción",
    # Varios objetos
    "orb": "orbe",
    "rune": "runa",
    "runic": "rúnico",
    "fang": "colmillo",
    "misc": "varios",
    "alchemy": "alquimia",
    "golem": "gólem",
    "star": "estrella",
    "starry": "estelar",
    "demonic": "demoníaco",
    "taint": "mácula",
    "venom": "veneno",
    "slime": "limo",
    "blaze": "llamarada",
    "strife": "conflicto",
    "ward": "guardia",
    "conjure": "conjurar",
    "spell": "hechizo",
    # Palabras de objetos que faltaban
    "coral": "coral",
    "orite": "orita",
    "trident": "tridente",
    "tribal": "tribal",
    "pestilent": "pestilente",
    "crimson": "carmesí",
    "ornate": "ornado",
    "helm": "yelmo",
    "gauntlets": "guanteletes",
    "longsword": "espada larga",
    "dagger": "daga",
    "mace": "maza",
    "ring": "anillo",
    "amulet": "amuleto",
    "cloak": "capa",
    "robe": "túnica",
    "quiver": "carcaj",
    "shard": "esquirlas",
    "totem": "tótem",
    "wand": "varita",
    "pickaxe": "pico",
    "longbow": "arco largo",
    "robe": "túnica",
    "boots": "botas",
    "belt": "cinturón",
    "shoes": "botas",
    "armor": "armadura",
    "helmet": "casco",
    "gloves": "guantes",
    "battleaxe": "hacha de batalla",
    "trident": "tridente",
    "waraxe": "hacha de guerra",
    "mindstar": "estrellamental",
    "torque": "torque",
    "staff": "bastón",
    "sling": "honda",
    "shot": "munición",
    "arrow": "flecha",
    "pouch": "bolsa",
    "tome": "tomo",
    "salve": "ungüento",
    "oil": "aceite",
    "serum": "sueño",
    "choker": "gargantilla",
    "girdle": "cinturón",
    "cuirass": "coraza",
    "treads": "zancos",
    "shroud": "mortaja",
    "phial": "frasco",
    "remnants": "vestigios",
    "scale mail": "malla de escamas",
    "robe": "túnica",
    # Palabras sueltas de egos/objects
    "aegis": "égida",
    "aether": "éter",
    "alchemist-gem": "gema de alquimista",
    "amnesia": "amnesia",
    "arcana": "arcana",
    "b.steel": "ac.acerado",
    "backstab": "apuñalar",
    "bounder": "saltador",
    "catburglar": "caterpillar",
    "clearmind": "menteclara",
    "color": "color",
    "corpselight": "luzcadavérica",
    "crackling": "crepitante",
    "decomp": "descomp",
    "dragon-helm": "yelmo-dragón",
    "dragonslayer": "matadragones",
    "eclipse": "eclipse",
    "eldoral": "eldoral",
    "enraging": "enfurecedor",
    "evisc": "despanz.",
    "eyal": "eyal",
    "fortif.": "fortif.",
    "galeforce": "fuerzaventolera",
    "gales": "ventoleras",
    "imbued": "imbuido",
    "impenetrable": "impenetrable",
    "implac.": "implac.",
    "implacable": "implacable",
    "infernal": "infernal",
    "ire": "ira",
    "iron.throne": "trono.hierro",
    "jade": "jade",
    "juggernaut": "juggernaut",
    "manastream": "flujomaná",
    "mastery": "maestría",
    "mitotic": "mitótico",
    "noble": "noble",
    "phasing": "fasear",
    "pilfering": "hurtador",
    "pixie": "duende",
    "polar": "polar",
    "precog": "precog",
    "prot": "prot",
    "rdef": "rdef",
    "regal": "regio",
    "regen": "regen",
    "reknor": "reknor",
    "sapper": "zapador",
    "scouring": "estropajo",
    "serend.": "serend.",
    "shaloren": "shaloren",
    "shrapnel": "metralla",
    "spinneret": "hilandera",
    "stinger": "aguijón",
    "temporal": "temporal",
    "thaloren": "thaloren",
    "toknor": "toknor",
    "tormentor": "atormentador",
    "torque": "torque",
    "treant": "treant",
    "troll": "trol",
    "tundral": "tundral",
    "umbral": "umbral",
    "valiance": "valentía",
    "woodsman": "leñador",
    "wyrms": "dragones",
    "wyrmwaxed": "encerado de dragón",
    "con": "con",
    "def": "def",
    "prot": "prot",
    "crit": "crit",
    "apr": "per",
    # Encuentros / Trampas / Eventos
    "sunwall": "murosolar",
    "boulder": "roca",
    "siphon": "sifón",
    "arcing spot": "punto chispeante",
    "dull area": "zona apagada",
    "water siphon": "sifón de agua",
    "Quit": "Salir",
    "Meteor!": "¡Meteoro!",
    "Grave": "Tumba",
    "Thunderstorm": "Tormenta eléctrica",
    "Lush forest": "Bosque frondoso",
    "Glowing Chest": "Cofre brillante",
    "Onslaught": "Asalto",
    # Logros
    "Treasure Hunter": "Cazatesoros",
    "Treasure Hoarder": "Acaparador de tesoros",
    "Exterminator": "Exterminador",
    "Bad Driver": "Mal Conductor",
    "Earth Master": "Maestro de la Tierra",
    "Huge Appetite": "Gran Apetito",
    "Headbanger": "Cabezazo",
    "Last Instant of Sanity": "Último Instante de Cordura",
    "Portal reaver": "Saqueador de portales",
    "Portal ender": "Acabador de portales",
    "Portal master": "Maestro de portales",
    "Flooder": "Inundador",
    "Anti-Antimagic!": "¡Anti-Antimagia!",
    "Squadmate": "Compañero",
    "Self-killer": "Suicida",
    "Explorer": "Explorador",
    "Orbituary": "Orbituario",
    "Oozemancer": "Maso de masas",
    "Pyromancer": "Piromante",
    "Cryomancer": "Criomante",
    "Lichform": "Forma de Lich",
    "Failed to save any escorted adventurers.": "No lograste salvar a ningún aventurero escoltado.",
    # Grids (suelos)
    "bamboo hut": "cabaña de bambú",
    "bamboo hut floor": "suelo de cabaña de bambú",
    "cliffside": "acantilado",
    "crack in spacetime": "grieta en el espacio-tiempo",
    "dune": "duna",
    "icecave": "cueva de hielo",
    "icy floor": "suelo helado",
    "lava": "lava",
    "molten lava": "lava fundida",
    "rock": "roca",
    "rockwall": "pared rocosa",
    "sand dune": "duna de arena",
    "sandwall": "muro de arena",
    "slime floor": "suelo de limo",
    "bool": "bool",
    "psitech": "psitécnica",
    # NPCs (criaturas)
    "Forest Troll Hedge-Wizard": "Mago Seto Trol del Bosque",
    "Malevolent Dimensional Jelly": "Gelatina Dimensional Malévola",
    "Phoenix": "Fénix",
    "Queen Ant": "Hormiga Reina",
    "Rat Lich": "Rata Liche",
    "anaconda": "anaconda",
    "animal": "animal",
    "ant": "hormiga",
    "archlich": "archiliche",
    "banshee": "banshee",
    "basilisk": "basilisco",
    "bat": "murciélago",
    "bear": "oso",
    "bee": "abeja",
    "beetle": "escarabajo",
    "boar": "jabalí",
    "brown bear": "oso pardo",
    "bug": "bicho",
    "cave bear": "oso de las cavernas",
    "centipede": "ciempiés",
    "cockroach": "cucaracha",
    "crab": "cangrejo",
    "crocodile": "cocodrilo",
    "deer": "ciervo",
    "dog": "perro",
    "dragon": "dragón",
    "eel": "anguila",
    "elephant": "elefante",
    "fire drake": "draco de fuego",
    "fox": "zorro",
    "frog": "rana",
    "giant": "gigante",
    "goat": "cabra",
    "grizzly bear": "oso pardo",
    "hawk": "halcón",
    "horse": "caballo",
    "hound": "sabueso",
    "ice worm": "gusano de hielo",
    "jelly": "gelatina",
    "king cobra": "cobra real",
    "lion": "león",
    "lizard": "lagarto",
    "mummy": "momía",
    "octopus": "pulpo",
    "panther": "pantera",
    "rabbit": "conejo",
    "rat": "rata",
    "raven": "cuervo",
    "scorpion": "escorpión",
    "shark": "tiburón",
    "skeleton": "esqueleto",
    "skull": "cráneo",
    "snake": "serpiente",
    "spell": "hechizo",
    "spider": "araña",
    "squirrel": "ardilla",
    "stone golem": "gólem de piedra",
    "storm": "tormenta",
    "swamp": "ciénaga",
    "sword": "espada",
    "turtle": "tortuga",
    "vampire": "vampiro",
    "vulture": "buitre",
    "warg": "huargo",
    "wasp": "avispa",
    "wolf": "lobo",
    "wraith": "espectro",
    "wyrm": "dragón",
    "zombie": "zombi",
    # Birth (clases/subclases)
    "Berserker": "Berserker",
    "Celestial": "Celestial",
    "Chronomancer": "Cronomante",
    "Construct": "Constructo",
    "Corruptor": "Corruptor",
    "Defiler": "Profanador",
    "Giant": "Gigante",
    "Golem": "Gólem",
    "Insane": "Insano",
    "Nightmare": "Pesadilla",
    "Normal": "Normal",
    "Roguelike": "Roguelike",
    "Adventure": "Aventura",
    "Exploration": "Exploración",
    "Easy": "Fácil",
    # Criaturas/NPCs que faltan
    "anaconda": "anaconda",
    "banshee": "banshee",
    "barrow wight": "espectro túmulo",
    "bee swarm": "enjambre de abejas",
    "brecklorn": "brecklorn",
    "brittle clear ooze": "líquido claro quebradizo",
    "crimson ooze": "líquido carmesí",
    "critter": "bicho",
    "cutpurse": "carterista",
    "daelach": "daelach",
    "devourer": "devorador",
    "dolleg": "dolleg",
    "dredge": "dredge",
    "drem master": "maestro drem",
    "dremling": "dremling",
    "dúathedlen": "dúathedlen",
    "elf": "elfo",
    "elven archer": "arquero élfico",
    "elven corruptor": "corruptor élfico",
    "elven guard": "guardia élfico",
    "elven mage": "mago élfico",
    "elven tempest": "tempestad élfica",
    "faeros": "faeros",
    "forge-giant": "gigante forjador",
    "ghast": "ghast",
    "ghoulking": "rey ghul",
    "grannor'vin": "grannor'vin",
    "grannor'vor": "grannor'vor",
    "gwelgoroth": "gwelgoroth",
    "horror": "horror",
    "hummerhorn": "cuernozumbador",
    "icy orc wyrmic": "dracónico orco helado",
    "ink squid": "calamar de tinta",
    "losgoroth": "losgoroth",
    "maelstrom": "marelstrom",
    "manaworm": "gusano de maná",
    "maulotaur": "maulotauro",
    "midge swarm": "enjambre de mosquitos",
    "mountain troll": "trol de montaña",
    "naga": "naga",
    "naga myrmidon": "mirmidón naga",
    "naga psyren": "psiren naga",
    "naga tide huntress": "cazadora de mareas naga",
    "ninurlhing": "ninurlhing",
    "ogre guard": "guardia ogro",
    "ogre warmaster": "maestro de guerra ogro",
    "onilug": "onilug",
    "orc": "orco",
    "orc cryomancer": "criomante orco",
    "orc elite berserker": "berserker de élite orco",
    "orc elite fighter": "luchador de élite orco",
    "orc fighter": "luchador orco",
    "orc grand summoner": "gran invocador orco",
    "orc mage-hunter": "cazamagos orco",
    "orc necromancer": "nigromante orco",
    "orc pyromancer": "piromante orco",
    "orc summoner": "invocador orco",
    "quasit": "quasit",
    "rattlesnake": "serpiente de cascabel",
    "ritch": "ritch",
    "ritch hunter": "cazador ritch",
    "ritch larva": "larva ritch",
    "sand-drake": "draco de arena",
    "sandworm": "gusano de arena",
    "sanguine horror": "horror sanguíneo",
    "shivgoroth": "shivgoroth",
    "skeleton magus": "mago esqueleto",
    "skeleton master archer": "arquero maestro esqueleto",
    "spiderkin": "arácnido",
    "spitting spider": "araña escupidora",
    "telugoroth": "telugoroth",
    "teluvorta": "teluvorta",
    "thaurhereg": "thaurhereg",
    "umber hulk": "gigante sombrío",
    "undead": "no-muerto",
    "ungolmor": "ungolmor",
    "uruivellas": "uruivellas",
    "venom drake": "draco de veneno",
    "venom drake hatchling": "cría de draco de veneno",
    "vermin": "alimaña",
    "weaver matriarch": "matriarca tejedora",
    "wisp": "fuego fatuo",
    "wretchling": "pústula",
    "xaren": "xaren",
    "xorn": "xorn",
    "yaech": "yaech",
    "yaech diver": "buzo yaech",
    "yaech hunter": "cazador yaech",
    "yaech mindslayer": "psiónico yaech",
    "yaech psion": "psión yaech",
    "ziguranth summoner": "invocador ziguranth",
    "ziguranth wyrmic": "dracónico ziguranth",
    # Birth / cosmeticos
    "Berserker": "Berserker",
    "Bikini / Mankini": "Bikini / Mankini",
    "Blond Beard 1": "Barba Rubia 1",
    "Blond Beard 5": "Barba Rubia 5",
    "Blond Mustache 1": "Bigote Rubio 1",
    "Blond Mustache 2": "Bigote Rubio 2",
    "Blond Mustache 3": "Bigote Rubio 3",
    "Blond Mustache 4": "Bigote Rubio 4",
    "Celestial": "Celestial",
    "Corruptor": "Corruptor",
    "Cracks": "Grietas",
    "Fangs 1": "Colmillos 1",
    "Fangs 2": "Colmillos 2",
    "Guts": "Tripas",
    "Iron Bolt": "Perno de Hierro",
    "Lich": "Lich",
    "Lich Eyes 1": "Ojos de Lich 1",
    "Lich Eyes 2": "Ojos de Lich 2",
    "Lich Eyes 3": "Ojos de Lich 3",
    "Lich Regalia 1": "Insignia de Lich 1",
    "Lich Regalia 10": "Insignia de Lich 10",
    "Lich Regalia 2": "Insignia de Lich 2",
    "Lich Regalia 3": "Insignia de Lich 3",
    "Lich Regalia 4": "Insignia de Lich 4",
    "Lich Regalia 5": "Insignia de Lich 5",
    "Lich Regalia 6": "Insignia de Lich 6",
    "Lich Regalia 7": "Insignia de Lich 7",
    "Lich Regalia 8": "Insignia de Lich 8",
    "Lich Regalia 9": "Insignia de Lich 9",
    "Mindslayer": "Psiónico",
    "Psionic": "Psiónico",
    "Redfur": "Pelirrojo",
    "Redhead Melinda": "Melinda Pelirroja",
    "Runic Golem": "Gólem Rúnico",
    "Rust": "Óxido",
    "Shalore": "Shalore",
    "Solipsist": "Solipsista",
    "Stone Warden": "Guardián Pétreo",
    "Tatoos 1": "Tatuajes 1",
    "Tatoos 2": "Tatuajes 2",
    "Tatoos 3": "Tatuajes 3",
    "Tatoos 4": "Tatuajes 4",
    "Tatoos 5": "Tatuajes 5",
    "Tatoos 6": "Tatuajes 6",
    "Tatoos 7": "Tatuajes 7",
    "Thalore": "Thalore",
    "Tutorial": "Tutorial",
    "Tutorial Adventurer": "Aventurero Tutorial",
    "Tutorial Basic": "Tutorial Básico",
    "Tutorial Human": "Humano Tutorial",
    "Tutorial Stats": "Estadísticas Tutorial",
    "Wanderer Seed": "Semilla Errante",
    "Wyrmic": "Dracónico",
    "Yeek": "Yeek",
    "base": "base",
    # Lore books
    "A Tranquil Meadow": "Un Prado Tranquilo",
    "Angolwen Fountain": "Fuente de Angolwen",
    "Beam Trap": "Trampa de Rayo",
    "Conclave Vault": "Bóveda del Cónclave",
    "Deep Bellow excavation report 1": "Informe de excavación Hondo Rugido 1",
    "Deep Bellow excavation report 2": "Informe de excavación Hondo Rugido 2",
    "Deep Bellow excavation report 3": "Informe de excavación Hondo Rugido 3",
    "Dragonsfire Trap": "Trampa de Fuego de Dragón",
    "Dust to Dust": "Polvo al Polvo",
    "Iron Throne Edict": "Edicto del Trono de Hierro",
    "Keepsake": "Recuerdo",
    "Kyless": "Kyless",
    "Kyless' Journal: First Entry": "Diario de Kyless: Primera Entrada",
    "Kyless' Journal: Second Entry": "Diario de Kyless: Segunda Entrada",
    "Kyless' Journal: Third Entry": "Diario de Kyless: Tercera Entrada",
    # Palabras de combate/logs
    "lightning": "relámpago",
    "bolt": "rayo",
    "striking": "golpeando",
    "flail": "mayal",
    "lashes": "azota",
    "tendrils": "tentáculos",
    "swell": "oleada",
    "positive": "positiva",
    "energy": "energía",
    # Palabras comunes del juego
    "damage": "daño",
    "talent": "talento",
    "spell": "hechizo",
    "level": "nivel",
    "cooldown": "enfriamiento",
    "range": "alcance",
    "radius": "radio",
    "duration": "duración",
    "speed": "velocidad",
    "power": "poder",
    "resistance": "resistencia",
    "immunity": "inmunidad",
    "chance": "probabilidad",
    "effect": "efecto",
    "target": "objetivo",
    "damage": "daño",
    "armor": "armadura",
    "defense": "defensa",
    "accuracy": "precisión",
    "weapon": "arma",
    "shield": "escudo",
}
