"""
Diccionario de términos del juego para ToME4-es.
Controla qué se traduce automáticamente y cómo.
"""

NO_TRANSLATE = {
    # Nombres de artefactos únicos
    "Acera",
    "Aetherwalk",
    "Anmalice",
    "Bloomsoul",
    "Blood-Edge",
    "Blood-Letter",
    "Blightstopper",
    "Butcher",
    "Cinderfeet",
    "Colaryem",
    "Corpathus",
    "Corpsebow",
    "Eclipse",
    "Exiler",
    "Firewalker",
    "Flamewrought",
    "Latafayn",
    "Lightbringer",
    "Linaniil",
    "Malediction",
    "Mankini",
    "Mercy",
    "Mnemonic",
    "Morrigor",
    "Nightsong",
    "Obliterator",
    "Radiance",
    "Shieldsmaiden",
    "Skullcleaver",
    "Sludgegrip",
    "Spellblade",
    "Spellcrusher",
    "Spelldrinker",
    "Stormfront",
    "Stormlash",
    "Summertide",
    "Swordbreaker",
    "Tarrasca",
    "Thunderfall",
    "Titanic",
    "Umbraphage",
    "Vilespawn",
    "Vox",
    "Wintertide",
    "Witch-Bane",
    "Wyrmbreath",
    "Rolf",
    "Weisman",
    # Nombres propios del juego
    "Maj'Eyal",
    "Eyal",
    "Sher'Tul",
    "ToME",
    "ToME4",
    "Amakthel",
    "Elandar",
    "Aeryn",
    "Urkis",
    "Voratun",
    "Stralite",
    "Mithril",
    # Zonas principales
    "Trollmire",
    "Kor'Pul",
    "Daikara",
    "Dreadfell",
    "Angolwen",
    "Zigur",
    "Derth",
    "Elvala",
    "Last Hope",
    "Iron Throne",
    "High Peak",
    "Lake of Nur",
    "Charred Scar",
}

FORCED_TERMS = {
    # Razas
    "Human": "Humano",
    "Elf": "Elfo",
    "Dwarf": "Enano",
    "Halfling": "Mediano",
    "Ogre": "Ogro",
    "Troll": "Trol",
    "Orc": "Orco",
    "Skeleton": "Esqueleto",
    "Ghoul": "Ghul",
    "Yeek": "Yeek",
    "Shalore": "Shalore",
    "Higher": "Superior",
    "Cornac": "Cornaco",
    "Thalore": "Thalore",
    "Drem": "Drem",
    "Krog": "Krog",
    "Doomelf": "Duendeldo",
    "Draconian": "Draconiano",
    # Clases
    "Warrior": "Guerrero",
    "Mage": "Mago",
    "Rogue": "Pícaro",
    "Archer": "Arquero",
    "Berserker": "Berserker",
    "Paladin": "Paladín",
    "Shadowblade": "Hoja Sombría",
    "Archmage": "Archimago",
    "Necromancer": "Nigromante",
    "Alchemist": "Alquimista",
    "Summoner": "Invocador",
    "Wilder": "Salvaje",
    "Sun Paladin": "Paladín Solar",
    "Anorithil": "Anoritil",
    "Corruptor": "Corruptor",
    "Reaver": "Despojador",
    "Doombringer": "Condenador",
    "Demonologist": "Demonólogo",
    "Writhing One": "Ser Retorcido",
    "Cursed": "Maldito",
    "Doomed": "Condenado",
    "Paradox Mage": "Mago de la Paradoja",
    "Temporal Warden": "Guardián Temporal",
    "Brawler": "Peleador",
    "Mind Slayer": "Psiónico",
    "Skirmisher": "Escaramuzador",
    "Marauder": "Mercenario",
    "Bulwark": "Baluarte",
    "Arcane Blade": "Hoja Arcana",
    "Adventurer": "Aventurero",
    "Annihilator": "Aniquilador",
    # Atributos
    "Strength": "Fuerza",
    "Dexterity": "Destreza",
    "Constitution": "Constitución",
    "Magic": "Magia",
    "Willpower": "Voluntad",
    "Cunning": "Astucia",
    # Talentos conocidos
    "Flame": "Llama",
    "Freeze": "Congelar",
    "Lightning": "Relámpago",
    "Manathrust": "Empuje de Maná",
    "Teleport": "Teletransporte",
    "Phase Door": "Puerta Dimensional",
    "Illuminate": "Iluminar",
    "Shatter": "Hacer Añicos",
    "Meteor": "Meteoro",
    # Tipos de daño
    "physical": "físico",
    "fire": "fuego",
    "cold": "frío",
    "lightning": "relámpago",
    "acid": "ácido",
    "nature": "naturaleza",
    "blight": "plaga",
    "arcane": "arcano",
    "light": "luz",
    "darkness": "oscuridad",
    "temporal": "temporal",
    "mind": "mente",
    "poison": "veneno",
    # Diálogos / UI
    "Hrmph.": "Hrmpf.",
    "Ok...": "Vale...",
    "error!": "¡error!",
    "Escort": "Escolta",
    "Warp": "Distorsión",
    "Temporal": "Temporal",
    "Armour Hardiness": "Fortaleza de Armadura",
    "Armour": "Armadura",
    "Primed Trigger": "Gatillo Preparado",
    "Normal Trigger": "Gatillo Normal",
    # Keywords de objetos (egos)
    "arcing": "arqueante",
    "vile": "vil",
    "elemental": "elemental",
    "tundral": "tundral",
    "manaburning": "quemamaná",
    "flaming": "llameante",
    "icy": "helado",
    "frozen": "congelado",
    "scorching": "abrasador",
    "shimmering": "brillante",
    "crackling": "crepitante",
    "caustic": "cáustico",
    "blighted": "maldito",
    "venomous": "venenoso",
    "verdant": "verdeante",
    "thorny": "espinoso",
    "wintry": "invernal",
    "infernal": "infernal",
    "ethereal": "etéreo",
    "brutal": "brutal",
    "cruel": "cruel",
    "swiftstrike": "golpeveloz",
    "mossy": "musgoso",
    "slimy": "baboso",
    "multihued": "multicolor",
    "windwalling": "muroviento",
    "shearing": "cortante",
    "piercing": "perforante",
    "sensing": "sensorial",
    "radiance": "resplandor",
    "dispeller": "disipador",
    "spiritwalk": "caminante espiritual",
    "sunseal": "sellosolar",
    "stormbringer": "portatormentas",
    "magehunters": "cazamagos",
    "voidstriker": "golpevacío",
    "dreamer": "soñador",
    "solipsist": "solipsista",
    "psionic": "psiónico",
    "psion": "psión",
    "timebroken": "tiempoquebrado",
    "bloodhexed": "sangrehechizada",
    "mindblast": "explosiónmental",
    "mindcage": "jaulamental",
    "mindweaver": "tejedoramental",
    "mindcraft": "artemental",
    "learwalker": "caminante del saber",
    "starseeker": "buscador de estrellas",
    "stargazer": "observador de estrellas",
    "starseer": "vidente de estrellas",
    "starseers": "videntes de estrellas",
    "voidstriker": "golpevacío",
    "warmaker": "hacedor de guerra",
    "warbringer": "portaguerra",
    "watchleader": "líder de guardia",
    "battlemaster": "maestro de batalla",
    "skylord": "señor del cielo",
    "swashbuckler": "espadachín",
    "gladiator": "gladiador",
    "champion": "campeón",
    "ravager": "devastador",
    "titan": "titán",
    "warlord": "señor de la guerra",
    "marshal": "mariscal",
    "marauder": "mercenario",
    "brawler": "peleador",
    "ranger": "explorador",
    "archer": "arquero",
    "rogue": "pícaro",
    "conjurer": "conjurador",
    "alchemist": "alquimista",
    "magewarrior": "magoguerrero",
    "magelord": "señor de la magia",
    "magery": "magia",
    # Subtipos de armas
    "battleaxe": "hacha de batalla",
    "longbow": "arco largo",
    "whip": "látigo",
    "mindstar": "estrellamental",
    "torque": "torque",
    "totem": "tótem",
    "staff": "bastón",
    "dagger": "daga",
    "greatsword": "espada enorme",
    "greatmaul": "mazo enorme",
    "waraxe": "hacha de guerra",
    "mace": "maza",
    "sword": "espada",
    "sling": "honda",
    "shot": "munición",
    "arrow": "flecha",
    "quiver": "carcaj",
    # Materiales
    "cashmere": "cachemira",
    "e.silk": "seda élfica",
    "e.wood": "madera élfica",
    "orichalcum": "oricalco",
    "voratun": "voratún",
    "stralite": "stralita",
    "mithril": "mitril",
    "dragonbone": "hueso de dragón",
    "elven-wood": "madera élfica",
    "yew": "tejo",
    "ash": "fresno",
    "elm": "olmo",
    "boned": "óseo",
    "iron": "hierro",
    "steel": "acero",
    "hardened": "endurecido",
    # Gemas
    "agate": "ágata",
    "aquamarine": "aguamarina",
    "citrine": "citrino",
    "garnet": "granate",
    "jade": "jade",
    "moonstone": "piedra lunar",
    "onyx": "ónix",
    "spinel": "espinela",
    "zircon": "circón",
    "amethyst": "amatista",
    "diamond": "diamante",
    "emerald": "esmeralda",
    "pearl": "perla",
    "quartz": "cuarzo",
    "ruby": "rubí",
    "sapphire": "zafiro",
    "topaz": "topacio",
    "opal": "ópalo",
    # Abreviaturas de stats
    "con": "con",
    "dex": "des",
    "def": "def",
    "mag": "mag",
    "wil": "vol",
    "cun": "ast",
    "str": "fuer",
    "apr": "per",
    "prot": "prot",
    "rdef": "rdef",
    "regen": "regen",
    "rejuv": "rejuve",
    "lite": "lum",
    "invigor.": "vigor.",
    "fortif.": "fortif.",
    "implac.": "implac.",
    "serend.": "serend.",
    # Stats completas
    "constitution": "constitución",
    "dexterity": "destreza",
    "cunning": "astucia",
    "willpower": "voluntad",
    "magic": "magia",
    "strength": "fuerza",
    "perception": "percepción",
    # Varios objetos
    "orb": "orbe",
    "rune": "runa",
    "runic": "rúnico",
    "fang": "colmillo",
    "misc": "varios",
    "alchemy": "alquimia",
    "golem": "gólem",
    "star": "estrella",
    "starry": "estelar",
    "demonic": "demoníaco",
    "taint": "mácula",
    "venom": "veneno",
    "slime": "limo",
    "blaze": "llamarada",
    "strife": "conflicto",
    "ward": "guardia",
    "conjure": "conjurar",
    "spell": "hechizo",
    # Palabras de objetos que faltaban
    "coral": "coral",
    "orite": "orita",
    "trident": "tridente",
    "tribal": "tribal",
    "pestilent": "pestilente",
    "crimson": "carmesí",
    "ornate": "ornado",
    "helm": "yelmo",
    "gauntlets": "guanteletes",
    "longsword": "espada larga",
    "dagger": "daga",
    "mace": "maza",
    "ring": "anillo",
    "amulet": "amuleto",
    "cloak": "capa",
    "robe": "túnica",
    "quiver": "carcaj",
    "shard": "esquirlas",
    "totem": "tótem",
    "wand": "varita",
    "pickaxe": "pico",
    "longbow": "arco largo",
    "robe": "túnica",
    "boots": "botas",
    "belt": "cinturón",
    "shoes": "botas",
    "armor": "armadura",
    "helmet": "casco",
    "gloves": "guantes",
    "battleaxe": "hacha de batalla",
    "trident": "tridente",
    "waraxe": "hacha de guerra",
    "mindstar": "estrellamental",
    "torque": "torque",
    "staff": "bastón",
    "sling": "honda",
    "shot": "munición",
    "arrow": "flecha",
    "pouch": "bolsa",
    "tome": "tomo",
    "salve": "ungüento",
    "oil": "aceite",
    "serum": "sueño",
    "choker": "gargantilla",
    "girdle": "cinturón",
    "cuirass": "coraza",
    "treads": "zancos",
    "shroud": "mortaja",
    "phial": "frasco",
    "remnants": "vestigios",
    "scale mail": "malla de escamas",
    "robe": "túnica",
    # Palabras sueltas de egos/objects
    "aegis": "égida",
    "aether": "éter",
    "alchemist-gem": "gema de alquimista",
    "amnesia": "amnesia",
    "arcana": "arcana",
    "b.steel": "ac.acerado",
    "backstab": "apuñalar",
    "bounder": "saltador",
    "catburglar": "caterpillar",
    "clearmind": "menteclara",
    "color": "color",
    "corpselight": "luzcadavérica",
    "crackling": "crepitante",
    "decomp": "descomp",
    "dragon-helm": "yelmo-dragón",
    "dragonslayer": "matadragones",
    "eclipse": "eclipse",
    "eldoral": "eldoral",
    "enraging": "enfurecedor",
    "evisc": "despanz.",
    "eyal": "eyal",
    "fortif.": "fortif.",
    "galeforce": "fuerzaventolera",
    "gales": "ventoleras",
    "imbued": "imbuido",
    "impenetrable": "impenetrable",
    "implac.": "implac.",
    "implacable": "implacable",
    "infernal": "infernal",
    "ire": "ira",
    "iron.throne": "trono.hierro",
    "jade": "jade",
    "juggernaut": "juggernaut",
    "manastream": "flujomaná",
    "mastery": "maestría",
    "mitotic": "mitótico",
    "noble": "noble",
    "phasing": "fasear",
    "pilfering": "hurtador",
    "pixie": "duende",
    "polar": "polar",
    "precog": "precog",
    "prot": "prot",
    "rdef": "rdef",
    "regal": "regio",
    "regen": "regen",
    "reknor": "reknor",
    "sapper": "zapador",
    "scouring": "estropajo",
    "serend.": "serend.",
    "shaloren": "shaloren",
    "shrapnel": "metralla",
    "spinneret": "hilandera",
    "stinger": "aguijón",
    "temporal": "temporal",
    "thaloren": "thaloren",
    "toknor": "toknor",
    "tormentor": "atormentador",
    "torque": "torque",
    "treant": "treant",
    "troll": "trol",
    "tundral": "tundral",
    "umbral": "umbral",
    "valiance": "valentía",
    "woodsman": "leñador",
    "wyrms": "dragones",
    "wyrmwaxed": "encerado de dragón",
    "con": "con",
    "def": "def",
    "prot": "prot",
    "crit": "crit",
    "apr": "per",
    # Palabras de combate/logs
    "lightning": "relámpago",
    "bolt": "rayo",
    "striking": "golpeando",
    "flail": "mayal",
    "lashes": "azota",
    "tendrils": "tentáculos",
    "swell": "oleada",
    "positive": "positiva",
    "energy": "energía",
    # Palabras comunes del juego
    "damage": "daño",
    "talent": "talento",
    "spell": "hechizo",
    "level": "nivel",
    "cooldown": "enfriamiento",
    "range": "alcance",
    "radius": "radio",
    "duration": "duración",
    "speed": "velocidad",
    "power": "poder",
    "resistance": "resistencia",
    "immunity": "inmunidad",
    "chance": "probabilidad",
    "effect": "efecto",
    "target": "objetivo",
    "damage": "daño",
    "armor": "armadura",
    "defense": "defensa",
    "accuracy": "precisión",
    "weapon": "arma",
    "shield": "escudo",
}
