"""
Diccionario de términos del juego para ToME4-es.
Controla qué se traduce automáticamente y cómo.
"""

NO_TRANSLATE = {
    # Nombres de artefactos únicos
    "Acera",
    "Aetherwalk",
    "Anmalice",
    "Bloomsoul",
    "Blood-Edge",
    "Blood-Letter",
    "Blightstopper",
    "Butcher",
    "Cinderfeet",
    "Colaryem",
    "Corpathus",
    "Corpsebow",
    "Eclipse",
    "Exiler",
    "Firewalker",
    "Flamewrought",
    "Latafayn",
    "Lightbringer",
    "Linaniil",
    "Malediction",
    "Mankini",
    "Mercy",
    "Mnemonic",
    "Morrigor",
    "Nightsong",
    "Obliterator",
    "Radiance",
    "Shieldsmaiden",
    "Skullcleaver",
    "Sludgegrip",
    "Spellblade",
    "Spellcrusher",
    "Spelldrinker",
    "Stormfront",
    "Stormlash",
    "Summertide",
    "Swordbreaker",
    "Tarrasca",
    "Thunderfall",
    "Titanic",
    "Umbraphage",
    "Vilespawn",
    "Vox",
    "Wintertide",
    "Witch-Bane",
    "Wyrmbreath",
    "Rolf",
    "Weisman",
    # Nombres propios del juego
    "Maj'Eyal",
    "Eyal",
    "Sher'Tul",
    "ToME",
    "ToME4",
    "Amakthel",
    "Elandar",
    "Aeryn",
    "Urkis",
    "Voratun",
    "Stralite",
    "Mithril",
    # Zonas principales
    "Trollmire",
    "Kor'Pul",
    "Daikara",
    "Dreadfell",
    "Angolwen",
    "Zigur",
    "Derth",
    "Elvala",
    "Last Hope",
    "Iron Throne",
    "High Peak",
    "Lake of Nur",
    "Charred Scar",
}

FORCED_TERMS = {
    # Razas
    "Human": "Humano",
    "Elf": "Elfo",
    "Dwarf": "Enano",
    "Halfling": "Mediano",
    "Ogre": "Ogro",
    "Troll": "Trol",
    "Orc": "Orco",
    "Skeleton": "Esqueleto",
    "Ghoul": "Ghul",
    "Yeek": "Yeek",
    "Shalore": "Shalore",
    "Higher": "Superior",
    "Cornac": "Cornaco",
    "Thalore": "Thalore",
    "Drem": "Drem",
    "Krog": "Krog",
    "Doomelf": "Duendeldo",
    "Draconian": "Draconiano",
    # Clases
    "Warrior": "Guerrero",
    "Mage": "Mago",
    "Rogue": "Pícaro",
    "Archer": "Arquero",
    "Berserker": "Berserker",
    "Paladin": "Paladín",
    "Shadowblade": "Hoja Sombría",
    "Archmage": "Archimago",
    "Necromancer": "Nigromante",
    "Alchemist": "Alquimista",
    "Summoner": "Invocador",
    "Wilder": "Salvaje",
    "Sun Paladin": "Paladín Solar",
    "Anorithil": "Anoritil",
    "Corruptor": "Corruptor",
    "Reaver": "Despojador",
    "Doombringer": "Condenador",
    "Demonologist": "Demonólogo",
    "Writhing One": "Ser Retorcido",
    "Cursed": "Maldito",
    "Doomed": "Condenado",
    "Paradox Mage": "Mago de la Paradoja",
    "Temporal Warden": "Guardián Temporal",
    "Brawler": "Peleador",
    "Mind Slayer": "Psiónico",
    "Skirmisher": "Escaramuzador",
    "Marauder": "Mercenario",
    "Bulwark": "Baluarte",
    "Arcane Blade": "Hoja Arcana",
    "Adventurer": "Aventurero",
    "Annihilator": "Aniquilador",
    # Atributos
    "Strength": "Fuerza",
    "Dexterity": "Destreza",
    "Constitution": "Constitución",
    "Magic": "Magia",
    "Willpower": "Voluntad",
    "Cunning": "Astucia",
    # Talentos conocidos
    "Flame": "Llama",
    "Freeze": "Congelar",
    "Lightning": "Relámpago",
    "Manathrust": "Empuje de Maná",
    "Teleport": "Teletransporte",
    "Phase Door": "Puerta Dimensional",
    "Illuminate": "Iluminar",
    "Shatter": "Hacer Añicos",
    "Meteor": "Meteoro",
    # Tipos de daño
    "physical": "físico",
    "fire": "fuego",
    "cold": "frío",
    "lightning": "relámpago",
    "acid": "ácido",
    "nature": "naturaleza",
    "blight": "plaga",
    "arcane": "arcano",
    "light": "luz",
    "darkness": "oscuridad",
    "temporal": "temporal",
    "mind": "mente",
    "poison": "veneno",
    # Diálogos / UI
    "Hrmph.": "Hrmpf.",
    "Ok...": "Vale...",
    "error!": "¡error!",
    "Escort": "Escolta",
    "Warp": "Distorsión",
    "Temporal": "Temporal",
    "Armour Hardiness": "Fortaleza de Armadura",
    "Armour": "Armadura",
    "Primed Trigger": "Gatillo Preparado",
    "Normal Trigger": "Gatillo Normal",
    # Keywords de objetos (egos)
    "arcing": "arqueante",
    "vile": "vil",
    "elemental": "elemental",
    "tundral": "tundral",
    "manaburning": "quemamaná",
    "flaming": "llameante",
    "icy": "helado",
    "frozen": "congelado",
    "scorching": "abrasador",
    "shimmering": "brillante",
    "crackling": "crepitante",
    "caustic": "cáustico",
    "blighted": "maldito",
    "venomous": "venenoso",
    "verdant": "verdeante",
    "thorny": "espinoso",
    "wintry": "invernal",
    "infernal": "infernal",
    "ethereal": "etéreo",
    "brutal": "brutal",
    "cruel": "cruel",
    "swiftstrike": "golpeveloz",
    "mossy": "musgoso",
    "slimy": "baboso",
    "multihued": "multicolor",
    "windwalling": "muroviento",
    "shearing": "cortante",
    "piercing": "perforante",
    "sensing": "sensorial",
    "radiance": "resplandor",
    "dispeller": "disipador",
    "spiritwalk": "caminante espiritual",
    "sunseal": "sellosolar",
    "stormbringer": "portatormentas",
    "magehunters": "cazamagos",
    "voidstriker": "golpevacío",
    "dreamer": "soñador",
    "solipsist": "solipsista",
    "psionic": "psiónico",
    "psion": "psión",
    "timebroken": "tiempoquebrado",
    "bloodhexed": "sangrehechizada",
    "mindblast": "explosiónmental",
    "mindcage": "jaulamental",
    "mindweaver": "tejedoramental",
    "mindcraft": "artemental",
    "learwalker": "caminante del saber",
    "starseeker": "buscador de estrellas",
    "stargazer": "observador de estrellas",
    "starseer": "vidente de estrellas",
    "starseers": "videntes de estrellas",
    "voidstriker": "golpevacío",
    "warmaker": "hacedor de guerra",
    "warbringer": "portaguerra",
    "watchleader": "líder de guardia",
    "battlemaster": "maestro de batalla",
    "skylord": "señor del cielo",
    "swashbuckler": "espadachín",
    "gladiator": "gladiador",
    "champion": "campeón",
    "ravager": "devastador",
    "titan": "titán",
    "warlord": "señor de la guerra",
    "marshal": "mariscal",
    "marauder": "mercenario",
    "brawler": "peleador",
    "ranger": "explorador",
    "archer": "arquero",
    "rogue": "pícaro",
    "conjurer": "conjurador",
    "alchemist": "alquimista",
    "magewarrior": "magoguerrero",
    "magelord": "señor de la magia",
    "magery": "magia",
    # Subtipos de armas
    "battleaxe": "hacha de batalla",
    "longbow": "arco largo",
    "whip": "látigo",
    "mindstar": "estrellamental",
    "torque": "torque",
    "totem": "tótem",
    "staff": "bastón",
    "dagger": "daga",
    "greatsword": "espada enorme",
    "greatmaul": "mazo enorme",
    "waraxe": "hacha de guerra",
    "mace": "maza",
    "sword": "espada",
    "sling": "honda",
    "shot": "munición",
    "arrow": "flecha",
    "quiver": "carcaj",
    # Materiales
    "cashmere": "cachemira",
    "e.silk": "seda élfica",
    "e.wood": "madera élfica",
    "orichalcum": "oricalco",
    "voratun": "voratún",
    "stralite": "stralita",
    "mithril": "mitril",
    "dragonbone": "hueso de dragón",
    "elven-wood": "madera élfica",
    "yew": "tejo",
    "ash": "fresno",
    "elm": "olmo",
    "boned": "óseo",
    "iron": "hierro",
    "steel": "acero",
    "hardened": "endurecido",
    # Gemas
    "agate": "ágata",
    "aquamarine": "aguamarina",
    "citrine": "citrino",
    "garnet": "granate",
    "jade": "jade",
    "moonstone": "piedra lunar",
    "onyx": "ónix",
    "spinel": "espinela",
    "zircon": "circón",
    "amethyst": "amatista",
    "diamond": "diamante",
    "emerald": "esmeralda",
    "pearl": "perla",
    "quartz": "cuarzo",
    "ruby": "rubí",
    "sapphire": "zafiro",
    "topaz": "topacio",
    "opal": "ópalo",
    # Abreviaturas de stats
    "con": "con",
    "dex": "des",
    "def": "def",
    "mag": "mag",
    "wil": "vol",
    "cun": "ast",
    "str": "fuer",
    "apr": "per",
    "prot": "prot",
    "rdef": "rdef",
    "regen": "regen",
    "rejuv": "rejuve",
    "lite": "lum",
    "invigor.": "vigor.",
    "fortif.": "fortif.",
    "implac.": "implac.",
    "serend.": "serend.",
    # Stats completas
    "constitution": "constitución",
    "dexterity": "destreza",
    "cunning": "astucia",
    "willpower": "voluntad",
    "magic": "magia",
    "strength": "fuerza",
    "perception": "percepción",
    # Varios objetos
    "orb": "orbe",
    "rune": "runa",
    "runic": "rúnico",
    "fang": "colmillo",
    "misc": "varios",
    "alchemy": "alquimia",
    "golem": "gólem",
    "star": "estrella",
    "starry": "estelar",
    "demonic": "demoníaco",
    "taint": "mácula",
    "venom": "veneno",
    "slime": "limo",
    "blaze": "llamarada",
    "strife": "conflicto",
    "ward": "guardia",
    "conjure": "conjurar",
    "spell": "hechizo",
    # Palabras de objetos que faltaban
    "coral": "coral",
    "orite": "orita",
    "trident": "tridente",
    "tribal": "tribal",
    "pestilent": "pestilente",
    "crimson": "carmesí",
    "ornate": "ornado",
    "helm": "yelmo",
    "gauntlets": "guanteletes",
    "longsword": "espada larga",
    "dagger": "daga",
    "mace": "maza",
    "ring": "anillo",
    "amulet": "amuleto",
    "cloak": "capa",
    "robe": "túnica",
    "quiver": "carcaj",
    "shard": "esquirlas",
    "totem": "tótem",
    "wand": "varita",
    "pickaxe": "pico",
    "longbow": "arco largo",
    "robe": "túnica",
    "boots": "botas",
    "belt": "cinturón",
    "shoes": "botas",
    "armor": "armadura",
    "helmet": "casco",
    "gloves": "guantes",
    "battleaxe": "hacha de batalla",
    "trident": "tridente",
    "waraxe": "hacha de guerra",
    "mindstar": "estrellamental",
    "torque": "torque",
    "staff": "bastón",
    "sling": "honda",
    "shot": "munición",
    "arrow": "flecha",
    "pouch": "bolsa",
    "tome": "tomo",
    "salve": "ungüento",
    "oil": "aceite",
    "serum": "sueño",
    "choker": "gargantilla",
    "girdle": "cinturón",
    "cuirass": "coraza",
    "treads": "zancos",
    "shroud": "mortaja",
    "phial": "frasco",
    "remnants": "vestigios",
    "scale mail": "malla de escamas",
    "robe": "túnica",
    # Palabras sueltas de egos/objects
    "aegis": "égida",
    "aether": "éter",
    "alchemist-gem": "gema de alquimista",
    "amnesia": "amnesia",
    "arcana": "arcana",
    "b.steel": "ac.acerado",
    "backstab": "apuñalar",
    "bounder": "saltador",
    "catburglar": "caterpillar",
    "clearmind": "menteclara",
    "color": "color",
    "corpselight": "luzcadavérica",
    "crackling": "crepitante",
    "decomp": "descomp",
    "dragon-helm": "yelmo-dragón",
    "dragonslayer": "matadragones",
    "eclipse": "eclipse",
    "eldoral": "eldoral",
    "enraging": "enfurecedor",
    "evisc": "despanz.",
    "eyal": "eyal",
    "fortif.": "fortif.",
    "galeforce": "fuerzaventolera",
    "gales": "ventoleras",
    "imbued": "imbuido",
    "impenetrable": "impenetrable",
    "implac.": "implac.",
    "implacable": "implacable",
    "infernal": "infernal",
    "ire": "ira",
    "iron.throne": "trono.hierro",
    "jade": "jade",
    "juggernaut": "juggernaut",
    "manastream": "flujomaná",
    "mastery": "maestría",
    "mitotic": "mitótico",
    "noble": "noble",
    "phasing": "fasear",
    "pilfering": "hurtador",
    "pixie": "duende",
    "polar": "polar",
    "precog": "precog",
    "prot": "prot",
    "rdef": "rdef",
    "regal": "regio",
    "regen": "regen",
    "reknor": "reknor",
    "sapper": "zapador",
    "scouring": "estropajo",
    "serend.": "serend.",
    "shaloren": "shaloren",
    "shrapnel": "metralla",
    "spinneret": "hilandera",
    "stinger": "aguijón",
    "temporal": "temporal",
    "thaloren": "thaloren",
    "toknor": "toknor",
    "tormentor": "atormentador",
    "torque": "torque",
    "treant": "treant",
    "troll": "trol",
    "tundral": "tundral",
    "umbral": "umbral",
    "valiance": "valentía",
    "woodsman": "leñador",
    "wyrms": "dragones",
    "wyrmwaxed": "encerado de dragón",
    "con": "con",
    "def": "def",
    "prot": "prot",
    "crit": "crit",
    "apr": "per",
    # Encuentros / Trampas / Eventos
    "sunwall": "murosolar",
    "boulder": "roca",
    "siphon": "sifón",
    "arcing spot": "punto chispeante",
    "dull area": "zona apagada",
    "water siphon": "sifón de agua",
    "Quit": "Salir",
    "Meteor!": "¡Meteoro!",
    "Grave": "Tumba",
    "Thunderstorm": "Tormenta eléctrica",
    "Lush forest": "Bosque frondoso",
    "Glowing Chest": "Cofre brillante",
    "Onslaught": "Asalto",
    # Logros
    "Treasure Hunter": "Cazatesoros",
    "Treasure Hoarder": "Acaparador de tesoros",
    "Exterminator": "Exterminador",
    "Bad Driver": "Mal Conductor",
    "Earth Master": "Maestro de la Tierra",
    "Huge Appetite": "Gran Apetito",
    "Headbanger": "Cabezazo",
    "Last Instant of Sanity": "Último Instante de Cordura",
    "Portal reaver": "Saqueador de portales",
    "Portal ender": "Acabador de portales",
    "Portal master": "Maestro de portales",
    "Flooder": "Inundador",
    "Anti-Antimagic!": "¡Anti-Antimagia!",
    "Squadmate": "Compañero",
    "Self-killer": "Suicida",
    "Explorer": "Explorador",
    "Orbituary": "Orbituario",
    "Oozemancer": "Maso de masas",
    "Pyromancer": "Piromante",
    "Cryomancer": "Criomante",
    "Lichform": "Forma de Lich",
    "Failed to save any escorted adventurers.": "No lograste salvar a ningún aventurero escoltado.",
    # Grids (suelos)
    "bamboo hut": "cabaña de bambú",
    "bamboo hut floor": "suelo de cabaña de bambú",
    "cliffside": "acantilado",
    "crack in spacetime": "grieta en el espacio-tiempo",
    "dune": "duna",
    "icecave": "cueva de hielo",
    "icy floor": "suelo helado",
    "lava": "lava",
    "molten lava": "lava fundida",
    "rock": "roca",
    "rockwall": "pared rocosa",
    "sand dune": "duna de arena",
    "sandwall": "muro de arena",
    "slime floor": "suelo de limo",
    "bool": "bool",
    "psitech": "psitécnica",
    # NPCs (criaturas)
    "Forest Troll Hedge-Wizard": "Mago Seto Trol del Bosque",
    "Malevolent Dimensional Jelly": "Gelatina Dimensional Malévola",
    "Phoenix": "Fénix",
    "Queen Ant": "Hormiga Reina",
    "Rat Lich": "Rata Liche",
    "anaconda": "anaconda",
    "animal": "animal",
    "ant": "hormiga",
    "archlich": "archiliche",
    "banshee": "banshee",
    "basilisk": "basilisco",
    "bat": "murciélago",
    "bear": "oso",
    "bee": "abeja",
    "beetle": "escarabajo",
    "boar": "jabalí",
    "brown bear": "oso pardo",
    "bug": "bicho",
    "cave bear": "oso de las cavernas",
    "centipede": "ciempiés",
    "cockroach": "cucaracha",
    "crab": "cangrejo",
    "crocodile": "cocodrilo",
    "deer": "ciervo",
    "dog": "perro",
    "dragon": "dragón",
    "eel": "anguila",
    "elephant": "elefante",
    "fire drake": "draco de fuego",
    "fox": "zorro",
    "frog": "rana",
    "giant": "gigante",
    "goat": "cabra",
    "grizzly bear": "oso pardo",
    "hawk": "halcón",
    "horse": "caballo",
    "hound": "sabueso",
    "ice worm": "gusano de hielo",
    "jelly": "gelatina",
    "king cobra": "cobra real",
    "lion": "león",
    "lizard": "lagarto",
    "mummy": "momía",
    "octopus": "pulpo",
    "panther": "pantera",
    "rabbit": "conejo",
    "rat": "rata",
    "raven": "cuervo",
    "scorpion": "escorpión",
    "shark": "tiburón",
    "skeleton": "esqueleto",
    "skull": "cráneo",
    "snake": "serpiente",
    "spell": "hechizo",
    "spider": "araña",
    "squirrel": "ardilla",
    "stone golem": "gólem de piedra",
    "storm": "tormenta",
    "swamp": "ciénaga",
    "sword": "espada",
    "turtle": "tortuga",
    "vampire": "vampiro",
    "vulture": "buitre",
    "warg": "huargo",
    "wasp": "avispa",
    "wolf": "lobo",
    "wraith": "espectro",
    "wyrm": "dragón",
    "zombie": "zombi",
    # Birth (clases/subclases)
    "Berserker": "Berserker",
    "Celestial": "Celestial",
    "Chronomancer": "Cronomante",
    "Construct": "Constructo",
    "Corruptor": "Corruptor",
    "Defiler": "Profanador",
    "Giant": "Gigante",
    "Golem": "Gólem",
    "Insane": "Insano",
    "Nightmare": "Pesadilla",
    "Normal": "Normal",
    "Roguelike": "Roguelike",
    "Adventure": "Aventura",
    "Exploration": "Exploración",
    "Easy": "Fácil",
    # Criaturas/NPCs que faltan
    "anaconda": "anaconda",
    "banshee": "banshee",
    "barrow wight": "espectro túmulo",
    "bee swarm": "enjambre de abejas",
    "brecklorn": "brecklorn",
    "brittle clear ooze": "líquido claro quebradizo",
    "crimson ooze": "líquido carmesí",
    "critter": "bicho",
    "cutpurse": "carterista",
    "daelach": "daelach",
    "devourer": "devorador",
    "dolleg": "dolleg",
    "dredge": "dredge",
    "drem master": "maestro drem",
    "dremling": "dremling",
    "dúathedlen": "dúathedlen",
    "elf": "elfo",
    "elven archer": "arquero élfico",
    "elven corruptor": "corruptor élfico",
    "elven guard": "guardia élfico",
    "elven mage": "mago élfico",
    "elven tempest": "tempestad élfica",
    "faeros": "faeros",
    "forge-giant": "gigante forjador",
    "ghast": "ghast",
    "ghoulking": "rey ghul",
    "grannor'vin": "grannor'vin",
    "grannor'vor": "grannor'vor",
    "gwelgoroth": "gwelgoroth",
    "horror": "horror",
    "hummerhorn": "cuernozumbador",
    "icy orc wyrmic": "dracónico orco helado",
    "ink squid": "calamar de tinta",
    "losgoroth": "losgoroth",
    "maelstrom": "marelstrom",
    "manaworm": "gusano de maná",
    "maulotaur": "maulotauro",
    "midge swarm": "enjambre de mosquitos",
    "mountain troll": "trol de montaña",
    "naga": "naga",
    "naga myrmidon": "mirmidón naga",
    "naga psyren": "psiren naga",
    "naga tide huntress": "cazadora de mareas naga",
    "ninurlhing": "ninurlhing",
    "ogre guard": "guardia ogro",
    "ogre warmaster": "maestro de guerra ogro",
    "onilug": "onilug",
    "orc": "orco",
    "orc cryomancer": "criomante orco",
    "orc elite berserker": "berserker de élite orco",
    "orc elite fighter": "luchador de élite orco",
    "orc fighter": "luchador orco",
    "orc grand summoner": "gran invocador orco",
    "orc mage-hunter": "cazamagos orco",
    "orc necromancer": "nigromante orco",
    "orc pyromancer": "piromante orco",
    "orc summoner": "invocador orco",
    "quasit": "quasit",
    "rattlesnake": "serpiente de cascabel",
    "ritch": "ritch",
    "ritch hunter": "cazador ritch",
    "ritch larva": "larva ritch",
    "sand-drake": "draco de arena",
    "sandworm": "gusano de arena",
    "sanguine horror": "horror sanguíneo",
    "shivgoroth": "shivgoroth",
    "skeleton magus": "mago esqueleto",
    "skeleton master archer": "arquero maestro esqueleto",
    "spiderkin": "arácnido",
    "spitting spider": "araña escupidora",
    "telugoroth": "telugoroth",
    "teluvorta": "teluvorta",
    "thaurhereg": "thaurhereg",
    "umber hulk": "gigante sombrío",
    "undead": "no-muerto",
    "ungolmor": "ungolmor",
    "uruivellas": "uruivellas",
    "venom drake": "draco de veneno",
    "venom drake hatchling": "cría de draco de veneno",
    "vermin": "alimaña",
    "weaver matriarch": "matriarca tejedora",
    "wisp": "fuego fatuo",
    "wretchling": "pústula",
    "xaren": "xaren",
    "xorn": "xorn",
    "yaech": "yaech",
    "yaech diver": "buzo yaech",
    "yaech hunter": "cazador yaech",
    "yaech mindslayer": "psiónico yaech",
    "yaech psion": "psión yaech",
    "ziguranth summoner": "invocador ziguranth",
    "ziguranth wyrmic": "dracónico ziguranth",
    # Birth / cosmeticos
    "Berserker": "Berserker",
    "Bikini / Mankini": "Bikini / Mankini",
    "Blond Beard 1": "Barba Rubia 1",
    "Blond Beard 5": "Barba Rubia 5",
    "Blond Mustache 1": "Bigote Rubio 1",
    "Blond Mustache 2": "Bigote Rubio 2",
    "Blond Mustache 3": "Bigote Rubio 3",
    "Blond Mustache 4": "Bigote Rubio 4",
    "Celestial": "Celestial",
    "Corruptor": "Corruptor",
    "Cracks": "Grietas",
    "Fangs 1": "Colmillos 1",
    "Fangs 2": "Colmillos 2",
    "Guts": "Tripas",
    "Iron Bolt": "Perno de Hierro",
    "Lich": "Lich",
    "Lich Eyes 1": "Ojos de Lich 1",
    "Lich Eyes 2": "Ojos de Lich 2",
    "Lich Eyes 3": "Ojos de Lich 3",
    "Lich Regalia 1": "Insignia de Lich 1",
    "Lich Regalia 10": "Insignia de Lich 10",
    "Lich Regalia 2": "Insignia de Lich 2",
    "Lich Regalia 3": "Insignia de Lich 3",
    "Lich Regalia 4": "Insignia de Lich 4",
    "Lich Regalia 5": "Insignia de Lich 5",
    "Lich Regalia 6": "Insignia de Lich 6",
    "Lich Regalia 7": "Insignia de Lich 7",
    "Lich Regalia 8": "Insignia de Lich 8",
    "Lich Regalia 9": "Insignia de Lich 9",
    "Mindslayer": "Psiónico",
    "Psionic": "Psiónico",
    "Redfur": "Pelirrojo",
    "Redhead Melinda": "Melinda Pelirroja",
    "Runic Golem": "Gólem Rúnico",
    "Rust": "Óxido",
    "Shalore": "Shalore",
    "Solipsist": "Solipsista",
    "Stone Warden": "Guardián Pétreo",
    "Tatoos 1": "Tatuajes 1",
    "Tatoos 2": "Tatuajes 2",
    "Tatoos 3": "Tatuajes 3",
    "Tatoos 4": "Tatuajes 4",
    "Tatoos 5": "Tatuajes 5",
    "Tatoos 6": "Tatuajes 6",
    "Tatoos 7": "Tatuajes 7",
    "Thalore": "Thalore",
    "Tutorial": "Tutorial",
    "Tutorial Adventurer": "Aventurero Tutorial",
    "Tutorial Basic": "Tutorial Básico",
    "Tutorial Human": "Humano Tutorial",
    "Tutorial Stats": "Estadísticas Tutorial",
    "Wanderer Seed": "Semilla Errante",
    "Wyrmic": "Dracónico",
    "Yeek": "Yeek",
    "base": "base",
    # Mensajes de combate objetos
    "#GOLD#A bolt of lightning fires from #Source#'s bow, striking #Target#!": "#GOLD#¡Un rayo sale del arco de #Source#, golpeando a #Target#!",
    "#ORCHID#Black tendrils from #Source# grab #Target#!": "#ORCHID#¡Tentáculos negros de #Source# agarran a #Target#!",
    "#Source#'s three headed flail lashes at #Target#!": "¡El mayal de tres cabezas de #Source# azota a #Target#!",
    "#GOLD#You feel a swell of positive energy!": "#GOLD#¡Sientes una oleada de energía positiva!",
    "#Source# burns #Target#!": "¡#Source# quema a #Target#!",
    "#VIOLET#You hear a door opening.": "#VIOLET#Oyes una puerta abriéndose.",
    "#VIOLET#You hear a mechanism clicking.": "#VIOLET#Oyes un mecanismo haciendo clic.",
    # Objetos finales
    "tattered cloak": "capa harapienta",
    "tattered robe": "túnica harapienta",
    "spider-silk robe": "túnica de seda de araña",
    "rotting longbow": "arco largo podrido",
    "corroded voratun gauntlets": "guanteletes de voratún oxidados",
    "gleaming voratun gauntlets": "guanteletes de voratún relucientes",
    "elven-silk cloak": "capa de seda élfica",
    "elven-silk robe": "túnica de seda élfica",
    "swirling orb": "orbe giratorio",
    "blink rune": "runa de parpadeo",
    "invisibility rune": "runa de invisibilidad",
    "manasurge rune": "runa de oleada de maná",
    "stormshield rune": "runa de escudo de tormenta",
    "teleportation rune": "runa de teletransporte",
    "acid wave rune": "runa de ola ácida",
    "vision rune": "runa de visión",
    "ethereal rune": "runa etérea",
    "demon bile": "bilis demoníaca",
    "troll guts": "tripas de trol",
    "wyrm saliva": "saliva de dragón",
    "faerlhing fang": "colmillo de faerlhing",
    "hummerhorn wing": "ala de cuernozumbador",
    "multi-hued wyrm scale": "escama de dragón multicolor",
    "vial of wight ectoplasm": "frasco de ectoplasma de wight",
    "viscous slime": "limo viscoso",
    "warg claw": "garra de huargo",
    "pouch of faeros ash": "bolsa de ceniza de faeros",
    "pouch of steel shots": "bolsa de munición de acero",
    "pouch of stralite shots": "bolsa de munición de stralita",
    "pouch of voratun shots": "bolsa de munición de voratún",
    "orb of command": "orbe de mando",
    "orb of scrying": "orbe de avistamiento",
    "titanic maul": "mazo titánico",
    "jagged, segmented, sword": "espada dentada y segmentada",
    "lapis lazuli": "lapislázuli",
    "alchemist lapis lazuli": "lapislázuli de alquimista",
    "alchemist turquoise": "turquesa de alquimista",
    "acid melee": "ácido cuerpo a cuerpo",
    "arcane melee": "arcano cuerpo a cuerpo",
    "blight melee": "plaga cuerpo a cuerpo",
    "fire melee": "fuego cuerpo a cuerpo",
    "light melee": "luz cuerpo a cuerpo",
    "lightning melee": "relámpago cuerpo a cuerpo",
    "manaburn melee": "quemamaná cuerpo a cuerpo",
    "slime melee": "limo cuerpo a cuerpo",
    "temporal melee": "temporal cuerpo a cuerpo",
    "temporal energize melee": "energizar temporal cuerpo a cuerpo",
    "gloom mind melee": "mente lúgubre cuerpo a cuerpo",
    "acid corrode melee": "ácido corrosivo cuerpo a cuerpo",
    "inc damage fire": "inc. daño fuego",
    "inc damage arcane": "inc. daño arcano",
    "resist arcane": "resistir arcano",
    "phys apr": "fís. per",
    "phys atk": "fís. atq",
    "phys crit": "fís. crit",
    "phys crit magnitude": "magnitud crit. fís.",
    "phys dam": "daño fís.",
    "stat con": "est. con",
    "stat cun": "est. ast",
    "stat dex": "est. des",
    "stat mag": "est. mag",
    "stat str": "est. fuer",
    "stat wil": "est. vol",
    "stave resists pen arcane": "resist. bastón pen. arcano",
    "g. warding": "g. guardia",
    # Timed effects (estados de combate) - los mas visibles
    "+Dazed": "Aturdido",
    "-Dazed": "Aturdimiento",
    "+Paralyzed": "Paralizado",
    "+Frozen": "Congelado",
    "+Shocked": "Electrocutado",
    "+Sleep": "Dormido",
    "+Stoned": "Petrificado",
    "+Haunted": "Embrujado",
    "+Panicked": "Aterrorizado",
    "+Overwhelmed": "Abrumado",
    "+Despair": "Desesperación",
    "+Nightmare": "Pesadilla",
    "+Cursed Wound": "Herida Maldita",
    "+Cursed Miasma": "Miasma Maldito",
    "+Maim": "Mutilar",
    "+Maimed": "Mutilado",
    "+Ravage": "Devastar",
    "+Ravage": "Devastado",
    "+Slow": "Ralentizado",
    "+Haste": "Acelerado",
    "+Regen": "Regeneración",
    "+Recovery": "Recuperación",
    "+Invis": "Invisible",
    "+Phased": "Faseado",
    "+Blink": "Parpadeo",
    "+Ward": "Guardia",
    "+Constricted": "Constreñido",
    "+Grappled": "Presa",
    "+Grappling": "Presionando",
    "+Off-balance": "Desequilibrado",
    "+Off-guard": "Descuidado",
    "+Bloodbath": "Baño de Sangre",
    "+Blood Lock": "Bloqueo de Sangre",
    "+Bone Shield": "Escudo Óseo",
    "+Bone Grab": "Agarre Óseo",
    "+Arcane Vortex": "Vórtice Arcano",
    "+Burning Shock": "Impacto Ardiente",
    "+Burning Hex": "Maldición Ardiente",
    "+Deadly Poison": "Veneno Mortal",
    "+Insidious Blight": "Plaga Insidiosa",
    "+Numbing Blight": "Plaga Entumecedora",
    "+Crippling Blight": "Plaga Debilitante",
    "+Domination Hex": "Maldición de Dominación",
    "+Crushing Hold": "Presa Aplastante",
    "+Sunder Armor": "Rompearmadura",
    "+Sunder Arms": "Rompebrazos",
    "+Dirty Fighting": "Pelea Sucia",
    "+Frozen Ground": "Suelo Helado",
    "+Stone Link": "Vínculo Pétreo",
    "+Stone Vine": "Enredadera Pétrea",
    "+Spine of the World": "Espina del Mundo",
    "+Probability Travel": "Viaje Probabilístico",
    "+Twist Fate": "Torcer el Destino",
    "+Spin Fate": "Hilar el Destino",
    "+Fateweaver": "Tejedor del Destino",
    "+Fold Fate": "Plegar el Destino",
    "+Set Up": "Preparado",
    "+Step Up": "Avance",
    "+Tether": "Atadura",
    "+Sever Lifeline": "Cortar Línea Vital",
    "+Mark of Light": "Marca de Luz",
    "+Suncloak": "Capa Solar",
    "+Light Burst": "Explosión de Luz",
    "+Draining Moonlight": "Drenar Luz Lunar",
    "+Shadowguard": "Guardia Sombría",
    "+Wraithform": "Forma Espectral",
    "+Fast As Lightning": "Rápido como el Rayo",
    "+Draconic Will": "Voluntad Drácónica",
    "+Ogric Wrath": "Ira Ógrica",
    "+Juggernaut": "Ariete",
    "+Invigorate": "Vigorizar",
    "+Assail": "Asaltar",
    "+Counter": "Contraatacar",
    "+Expose Weakness": "Exponer Debilidad",
    "+Mana Overflow": "Desbordamiento de Maná",
    "+Arcane Supremacy": "Supremacía Arcana",
    "+Hidden Ressources": "Recursos Ocultos",
    "+Slippery Ground": "Suelo Resbaladizo",
    "+Slippery Moss": "Musgo Resbaladizo",
    "+Thorny Skin": "Piel Espinosa",
    "+Mucus": "Moco",
    "+Vampire Mark": "Marca de Vampiro",
    "+Undeath Surge": "Embate de No-Muerte",
    "+Rigor Mortis": "Rigor Mortis",
    "+Wasting": "Consumir",
    "+Retched": "Arcadas",
    "+Smeared": "Manchado",
    "+Smearing": "Manchando",
    "+Overload": "Sobrecarga",
    "+Purge": "Purgar",
    "+Purging": "Purgando",
    "+Brainlocked": "Mente Bloqueada",
    "+Lobotomized": "Lobotomizado",
    "+Mind Parasite": "Parásito Mental",
    "+Mind Link": "Vínculo Mental",
    "+Dominant Will": "Voluntad Dominante",
    "+Fade From Time": "Desvanecerse del Tiempo",
    "+Faded": "Desvanecido",
    "+Aether Breach": "Brecha de Éter",
    "+Abyssal Shroud": "Mortaja Abisal",
    "+Ethereal": "Etéreo",
    "+Primal": "Primordial",
    "+Curse": "Maldición",
    "+Bane": "Perdición",
    "+Aura": "Aura",
    "+Celestial": "Celestial",
    "+Escape!": "¡Huida!",
    "+Anchor": "Ancla",
    "+Maelstrom": "Maelstrom",
    "+Cauterize": "Cauterizar",
    "+Flawed": "Defectuoso",
    "+Demon": "Demonio",
    "+Dimensional": "Dimensional",
    "+Unstable": "Inestable",
    "+Feedback": "Retroalimentación",
    "+Phase": "Fase",
    "+Temporal Fugue": "Fuga Temporal",
    "+Webs of Fate": "Telarañas del Destino",
    "+Spydric Poison": "Veneno Arácnido",
    "+Crippling Poison": "Veneno Debilitante",
    "+Snipe": "Francotirar",
    "+Sentinel": "Centinela",
    "+Ghost Walk": "Paso Fantasmal",
    "+Suffocating": "Asfixiando",
    "+Touch of Death": "Toque de Muerte",
    "+Breach": "Brecha",
    "+Sedated": "Sedado",
    "aura": "aura",
    "bane": "perdición",
    "celestial": "celestial",
    "cripple": "debilitar",
    "eidolon": "eidolon",
    "elemental": "elemental",
    "ghoul": "ghul",
    "grapple": "presa",
    "invulnerable": "in vulnerable",
    "meta": "meta",
    "moss": "musgo",
    "necrotic": "necrótico",
    "regen": "regen",
    "tempo": "tempo",
    "temporal": "temporal",
    "thaumaturgy": "taumaturgia",
    "timeport": "teletiempo",
    ", arcane": "arcano",
    ", temporal": "temporal",
    # Timed effects que empiezan con minuscula (sueltos)
    "+CLOAK OF DECEPTION": "CAPA DE ENGAÑO",
    "-CLOAK OF DECEPTION": "CAPA DE ENGAÑO",
    "+Dim": "Oscurecer",
    "+Pitch": "Negrura",
    "+Lightburn": "Quemadura de Luz",
    "+Lightblight": "Plaga de Luz",
    "+Hunter": "Cazador",
    "+Phoenix": "Fénix",
    "+Manaworm": "Gusano de Maná",
    "+Quick": "Rápido",
    "+Braided": "Trenzado",
    # Talents restantes
    "thaumaturgy": "taumaturgia",
    "terror": "terror",
    "eclipse": "eclipse",
    "hexes": "maldiciones",
    "drolem": "drolem",
    "golemancy": "golemancia",
    "spectre": "espectro",
    "taints": "máculas",
    "scoundrel": "canalla",
    "uber": "uber",
    "animus": "ánimus",
    "@Source@ shrieks.": "@Source@ chilla.",
    "temporal-hound": "sabueso temporal",
    # Lore lugares
    "daikara": "Daikara",
    "derth": "Derth",
    "kor'pul": "Kor'Pul",
    "ardhungol": "Ardhungol",
    "dogroth caldera": "caldera Dogroth",
    "slazish fens": "pantanos Slazish",
    "southspar": "Southspar",
    "highfin": "Highfin",
    "rhaloren": "Rhaloren",
    "spydrë": "Spydrë",
    "arena": "arena",
    "conch (1)": "caracola (1)",
    "zigur": "Zigur",
    "eyal": "Eyal",
    "slain master": "maestro asesinado",
    # UI Labels / Dialogos mod/class
    "Hotkeys": "Atajos",
    "Minimap": "Minimapa",
    "Pickup": "Recoger",
    "Sustained": "Sostenido",
    "Whisper": "Susurro",
    "Reset UI": "Restablecer IU",
    "Game Log": "Registro de Juego",
    "Show known Lore": "Mostrar Lore conocido",
    "Toggle:": "Alternar:",
    "Quick Weapon Swap:": "Cambio Rápido de Arma:",
    "M. power:": "P. mágico:",
    "M. save:": "M. salvación:",
    "P. power:": "P. físico:",
    "S. power:": "P. espiritual:",
    "S. save:": "S. salvación:",
    "Stroll": "Paseo",
    "Donator": "Donante",
    "Diggable": "Excavable",
    "Full Turn": "Turno Completo",
    "Drains": "Drena",
    "Lit": "Iluminado",
    "Feedback": "Retroalimentación",
    "Fortress Energy": "Energía de Fortaleza",
    "Imperium courrier": "Mensajero del Imperio",
    "Information on the failed zone and level dumped to the log file.": "Información de la zona y nivel fallidos volcada al archivo de registro.",
    "Debug the problem (move to the failed zone/level)": "Depurar el problema (ir a la zona/nivel fallido)",
    "Tales of Maj'Eyal Achievements": "Logros de Tales of Maj'Eyal",
    "Tales of Maj'Eyal Lore": "Lore de Tales of Maj'Eyal",
    "+1 Prodigy Point": "+1 Punto de Prodigio",
    "OVERKILL": "SOBREMATAR",
    "Pacifist": "Pacifista",
    "Headhunter": "Cazarecompensas",
    "Dream Hunter": "Cazador de Sueños",
    "Mirror Match": "Combate Espejo",
    "Multi-hued Wyrmic": "Dracónico Multicolor",
    "#YELLOW#On weapon crit:#LAST#": "#YELLOW#Al crit. con arma:#LAST#",
    "#YELLOW#On weapon hit:#LAST#": "#YELLOW#Al golpear con arma:#LAST#",
    "#YELLOW#On weapon kill:#LAST#": "#YELLOW#Al matar con arma:#LAST#",
    "#WHITE#Shield:": "#WHITE#Escudo:",
    "#7fffd4#Feedback:": "#7fffd4#Retroalimentación:",
    "#c00000#Un.body :": "#c00000#Sin.cuerpo:",
    "#FF0000#Drop some of your items.": "#FF0000#Suelta algunos de tus objetos.",
    "#VIOLET#": "#VIOLET#",
    # Item quality tags
    "[Boss]": "[Jefe]",
    "[MiniBoss]": "[Subjefe]",
    "[Final]": "[Final]",
    "[Unique]": "[Único]",
    "[Random Unique]": "[Único Aleatorio]",
    "[Legendary]": "[Legendario]",
    "[Godslayer]": "[Mata Dioses]",
    "[Plot Item]": "[Objeto de Trama]",
    "[Cosmetic Item]": "[Objeto Cosmético]",
    # Creature/item descriptors
    "actor": "actor",
    "battered": "estropeado",
    "dims": "oscurece",
    "dodge": "esquivar",
    "elite": "élite",
    "gargantuan": "gigantesco",
    "gleaming": "reluciente",
    "masteries": "maestrías",
    "melee/personal": "cuerpo a cuerpo/personal",
    "mental": "mental",
    "neutral": "neutral",
    "normal": "normal",
    "scintillating": "centelleante",
    "sigiled": "sigilado",
    "spot": "lugar",
    "stat": "estadística",
    "to psi": "a psi",
    "#Source# misses #Target#.": "#Source# falla a #Target#.",
    "#Source# misses #target#.": "#Source# falla a #target#.",
    "#Target# evades #Source#.": "#Target# esquiva a #Source#.",
    "#CRIMSON##Source# leeches life from #Target#!:": "#CRIMSON##Source# drena vida de #Target#!",
    "#CRIMSON##Source# teleports some damage to #Target#!:": "#CRIMSON##Source# teletransporta daño a #Target#!",
    "#RED##Source# is unstoppable!:": "#RED##Source# es imparable!",
    "#Target#'s": "de #Target#",
    # Nombres de tiendas y NPCs
    "axe smith": "herrero de hachas",
    "mace smith": "herrero de mazas",
    "armour smith": "herrero de armaduras",
    "staves and wands store": "tienda de bastones y varitas",
    "rune store": "tienda de runas",
    "staves": "bastones",
    "mindstar collector": "coleccionista de estrellas mentales",
    "human farmer": "granjero humano",
    "derth guard": "guardia de Derth",
    "elvala guard": "guardia de Elvala",
    "lumberjack": "leñador",
    "gem crafter": "artesano de gemas",
    "Master alchemist": "Maestro alquimista",
    "master slinger": "maestro hondero",
    "slinger": "hondero",
    "hexer": "hechicero",
    "pyromancer": "piromante",
    "cryomancer": "criomante",
    "geomancer": "geomante",
    "Tanner": "Peletero",
    "Swordsmith": "Espadero",
    "Tailor": "Sastre",
    "Runemaster": "Maestro de Runas",
    "Armoury": "Armería",
    # Zonas / lugares
    "cobblestone road": "camino adoquinado",
    "lava pit": "pozo de lava",
    "polar cap": "casquete polar",
    "orb pedestal (dragon)": "pedestal de orbe (dragón)",
    "Exploratory Farportal": "Portal Lejano Exploratorio",
    "anguished shrieks of the dying": "gritos angustiados de los moribundos",
    "arena": "arena",
    "sandworm lair": "guarida de gusano de arena",
    "dreamscape": "paisaje onírico",
    "trollmire": "Trollmire",
    "angolwen": "Angolwen",
    "shatur": "Shatur",
    "twilight": "crepúsculo",
    "oasis": "oasis",
    "shimmer ingame": "brillar en juego",
    # Conceptos del juego
    "solipsism": "solipsismo",
    "trance": "trance",
    "necrosis": "necrosis",
    "thuggery": "gamberrismo",
    "grappling": "presa",
    "voracity": "voracidad",
    "kinetic mastery": "maestría cinética",
    "psi-fighting": "lucha psiónica",
    "thievery": "hurto",
    "artifice": "artificio",
    "lure": "señuelo",
    "gloom": "oscuridad",
    "ooze": "limo",
    "twilight": "crepúsculo",
    "firestorm": "tormenta de fuego",
    "flux": "flujo",
    "timetravel": "viaje en el tiempo",
    "sanguisuge": "sanguijuela",
    "aura": "aura",
    "eidolon": "eidolon",
    "tempo": "tempo",
    "Xhaiak": "Xhaiak",
    "Shiaak": "Shiaak",
    "xhaiak arachnomancer": "araenomante xhaiak",
    "shiaak venomblade": "hoja venenosa shiaak",
    "weaver hatchling": "cría de tejedor",
    "orb spinner": "girandorbe",
    "orb weaver": "tejedor de orbes",
    "naga tidewarden": "guardamareas naga",
    "naga tidecaller": "invocamareas naga",
    "naga nereid": "nereida naga",
    "naga invasion coral portal": "portal de coral de invasión naga",
    "yeek mindslayer": "psiónico yeek",
    "yeek psionic": "psiónico yeek",
    "shalore rune master": "maestro de runas shalore",
    "thalore hunter": "cazador thalore",
    "thalore wilder": "salvaje thalore",
    "multihued wyrmic": "dracónico multicolor",
    "ogric abomination": "abominación ógrica",
    "frail mouse": "ratón frágil",
    "log of healer Astelrid": "diario del curandero Astelrid",
    "hastily written log": "diario escrito apresuradamente",
    "ominous, dark runed staff": "bastón oscuro y siniestro con runas",
    "test glyph": "glifo de prueba",
    "tutorial": "tutorial",
    "tutorial2": "tutorial2",
    "tutorial3": "tutorial3",
    "tutorial4": "tutorial4",
    "tutorial5": "tutorial5",
    "tutorial6": "tutorial6",
    "sylvan": "silvano",
    "hewn": "tallado",
    "unhewn": "sin tallar",
    "slimey": "limoso",
    "molten": "fundido",
    "trinket": "baratija",
    "spectator": "espectador",
    "rittch impaler": "empalador ritch",
    "sandworm burrower": "excavador de gusano de arena",
    # Lore books
    "Catch @himher@!": "¡Atrapa a @himher@!",
    "athanme": "athame",
    # Lore books
    "A Tranquil Meadow": "Un Prado Tranquilo",
    "Angolwen Fountain": "Fuente de Angolwen",
    "Beam Trap": "Trampa de Rayo",
    "Conclave Vault": "Bóveda del Cónclave",
    "Deep Bellow excavation report 1": "Informe de excavación Hondo Rugido 1",
    "Deep Bellow excavation report 2": "Informe de excavación Hondo Rugido 2",
    "Deep Bellow excavation report 3": "Informe de excavación Hondo Rugido 3",
    "Dragonsfire Trap": "Trampa de Fuego de Dragón",
    "Dust to Dust": "Polvo al Polvo",
    "Iron Throne Edict": "Edicto del Trono de Hierro",
    "Keepsake": "Recuerdo",
    "Kyless": "Kyless",
    "Kyless' Journal: First Entry": "Diario de Kyless: Primera Entrada",
    "Kyless' Journal: Second Entry": "Diario de Kyless: Segunda Entrada",
    "Kyless' Journal: Third Entry": "Diario de Kyless: Tercera Entrada",
    # Palabras de combate/logs
    "lightning": "relámpago",
    "bolt": "rayo",
    "striking": "golpeando",
    "flail": "mayal",
    "lashes": "azota",
    "tendrils": "tentáculos",
    "swell": "oleada",
    "positive": "positiva",
    "energy": "energía",
    # Palabras comunes del juego
    "damage": "daño",
    "stamina": "resistencia",
    "Stamina": "Resistencia",
    "talent": "talento",
    "spell": "hechizo",
    "level": "nivel",
    "cooldown": "enfriamiento",
    "range": "alcance",
    "radius": "radio",
    "duration": "duración",
    "speed": "velocidad",
    "power": "poder",
    "resistance": "resistencia",
    "immunity": "inmunidad",
    "chance": "probabilidad",
    "effect": "efecto",
    "target": "objetivo",
    "damage": "daño",
    "armor": "armadura",
    "defense": "defensa",
    "accuracy": "precisión",
    "weapon": "arma",
    "shield": "escudo",
}

POST_PROCESS = [
    # ──────────────────────────────────────────────────────────────────
    # CORRECCIONES DE "USTED" → "TÚ" (formal → informal)
    # ToME usa "tú" como estándar español. LibreTranslate tiende a "usted".
    # ──────────────────────────────────────────────────────────────────
    # Pronombres y posesivos
    (r"\bUsted\b", "Tú"),
    (r"\busted\b", "tú"),
    (r"\bTu\b(?=\s+[a-z])", "Tu"),  # "Tu puedes" no debe cambiar, pero cuidado
    (
        r"\btu\b(?=\s+(?:puedes|tienes|eres|estás|has|haz|sé))",
        "tú",
    ),  # "tu puedes" → "tú puedes"
    # Genérico: "su <sustantivo>" → "tu <sustantivo>"
    (r"\bsu\b(?=\s+[a-záéíóúñ])", "tu"),
    (r"\bSu\b(?=\s+[a-záéíóúñ])", "Tu"),
    (r"\bsuy[oa]s?\b", "tuyo"),
    (
        r"\ble\b(?=\s+(?:afecta|otorga|daña|causa|inflige|concede|aplica|reduce|aumenta|otorgar))",
        "te",
    ),
    (
        r"\bLe\b(?=\s+(?:afecta|otorga|daña|causa|inflige|concede|aplica|reduce|aumenta))",
        "Te",
    ),
    (
        r"\bse\b(?=\s+(?:aplica|activa|reduce|convierte|vuelve|vuelva|encuentra|encuentre|considera|consideren))",
        "se",
    ),  # solo cuando es reflexivo válido
    # Verbos conjugados en 3ª persona → 2ª persona (usted → tú)
    (
        r"\bpuede\b(?=\s+(?:ser|tener|usar|hacer|atacar|lanzar|invocar|afectar|curar|dañar|infligir|otorgar|aumentar|reducir|absorber|proteger|mejorar|activar))",
        "puedes",
    ),
    (r"\btiene\b(?=\s+(?:un|una|el|la|los|las|que|la capacidad))", "tienes"),
    (
        r"\b(?:Él|Ella)\b\s+(?:puede|tiene|hace|está|va|usa|ataca|lanza)",
        "",
    ),  # quitar "Él/Ella" donde es genérico
    # Casos especiales de verbos
    (
        r"\b(?:hace|hace que)\b(?=\s+(?:que|un|una|el|la))",
        lambda m: {"hace que": "hace que", "hace": "hace"}[m.group(0)],
    ),  # mantener
    (
        r"\bestá\b(?=\s+(?:bajo|siendo|en|dentro|afectado|marcado|bendecido|maldito|paralizado|congelado|aturdido|envenenado|ralentizado))",
        "estás",
    ),
    (r"\bes\b(?=\s+(?:un|una|el|la|muy|bastante|poco|el|más))", "eres"),
    (r"\bEres\b", "Eres"),
    # ──────────────────────────────────────────────────────────────────
    # CORRECCIONES DE TRADUCCIÓN LITERAL ERRÓNEA DE LIBRETRANSLATE
    # ──────────────────────────────────────────────────────────────────
    # "armour" → "armadura" (LT a veces da "amor")
    (r"\bamor\b", "armadura"),
    (r"\bAmor\b", "Armadura"),
    # "caster" → "lanzador" (LT: "castra")
    (r"\bcastra\b", "lanzador"),
    # "spell" → "hechizo" (LT: "sortilegio")
    (r"\bsortilegio\b", "hechizo"),
    (r"\bSortilegio\b", "Hechizo"),
    # "summoned" → "invocado" (LT: "citado")
    (r"\bcitado\b(?=\s+(?:un|una|por|el|la))", "invocado"),
    # "turns" → "turnos" (LT: "giros")
    (r"\bgiros\b", "turnos"),
    # "chance" → "probabilidad" (contextos no traducidos)
    (r"\bchance\b", "probabilidad"),
    (r"\bChance\b", "Probabilidad"),
    # ──────────────────────────────────────────────────────────────────
    # TÉRMINOS DE JUEGO QUE LT MALTRADUCE SISTEMÁTICAMENTE
    # ──────────────────────────────────────────────────────────────────
    # Daño
    (r"\bdañar\b", "daño"),
    (r"\bDañar\b", "Daño"),
    # Body/Health
    (r"\bcuerpo a cuerpo\b", "cuerpo a cuerpo"),
    # "focus" / "rate"
    (r"\btasa\b", "tasa"),
    # Preposiciones incorrectas
    (r"resistencia por\b", "resistencia a"),
    (r"inmunidad por\b", "inmunidad a"),
    (r"daño por\b", "daño a"),
    (r"penetración por\b", "penetración a"),
    # Artículos incorrectos
    (r"\bel armadura\b", "la armadura"),
    (r"\bun armadura\b", "una armadura"),
    (r"\bun daño\b", "un daño"),
    (r"\bun hechizo\b", "un hechizo"),
    (r"\bun arma\b", "un arma"),
    # Pointos → puntos
    (r"\bpointos\b", "puntos"),
    # ──────────────────────────────────────────────────────────────────
    # MEJORAS DE FLUIDEZ EN ESPAÑOL
    # ──────────────────────────────────────────────────────────────────
    # "the" traducido como artículo extra
    (r"\bel enemigo\b", "al enemigo"),
    (r"\bla víctima\b", "a la víctima"),
    (r"\b(el|la) atacante\b", lambda m: m.group(1) + " atacante"),
    # "estacking" → "apilamiento"
    (r"\bestacking\b", "apilamiento"),
    # "del enemigo" cuando es posesivo válido
    (r"\bdel objetivo\b", "del objetivo"),
    # "de daño" redundante
    (r"\bde daño de\b", "de daño de"),
    # Plurales incorrectos
    (r"poderes\b", "poderes"),
    (r"hechizos\b", "hechizos"),
    # "golpes" como verbo → "golpea" (LT: "hits" → "golpes" sustantivo)
    (r"@\w+@\s+golpes\s+@\w+@", lambda m: m.group(0).replace(" golpes ", " golpea ")),
    # "daños" → "daño" cuando va tras número (daño computado, singular en juegos)
    (r"\b(\d+)\s+daños\b", r"\1 daño"),
    (r"\bdaños\b(?=\s+(?:!|\.|,|$|por|de|a|en|con))", "daño"),
    # "Trata" → "Inflige" (LT: "Deals X damage" → "Trata X daño" en vez de "Inflige")
    (
        r"\bTrata\s+(?:el|un|la|una)\s+\d+",
        lambda m: m.group(0).replace("Trata", "Inflige"),
    ),
    (
        r"\btrata\s+(?:el|un|la|una)\s+\d+",
        lambda m: m.group(0).replace("trata", "inflige"),
    ),
    # ──────────────────────────────────────────────────────────────────
    # NOMBRES DE ESTADÍSTICAS EN INGLÉS SUELTOS
    # (cogidos por LT cuando aparecen en mitad de frase sin contexto)
    # ──────────────────────────────────────────────────────────────────
    (r"\bmelee\b", "cuerpo a cuerpo"),
    (r"\bMelee\b", "Cuerpo a cuerpo"),
    (r"\bmelea\b", "cuerpo a cuerpo"),  # LT mangla "melee" → "melea"
    (r"\bMelea\b", "Cuerpo a cuerpo"),
    (r"\branged\b", "a distancia"),
]

# Añadir también tu/usted extra para verbos comunes
_VERB_TU = {
    "puede": "puedes",
    "tiene": "tienes",
    "está": "estás",
    "hace": "haces",
    "va": "vas",
    "usa": "usas",
    "ataca": "atacas",
    "lanza": "lanzas",
    "invoca": "invocas",
    "cura": "curas",
    "otorga": "otorgas",
    "concede": "concedes",
    "aplica": "aplicas",
    "reduce": "reduces",
    "aumenta": "aumentas",
    "crea": "creas",
    "convierte": "conviertes",
    "absorbe": "absorbes",
    "gana": "ganas",
    "pierde": "pierdes",
}

# Generar patrones de verbos para POST_PROCESS
# Convierte 3ª persona (él/ella/usted) a 2ª persona (tú)
# Excluye casos impersonales con "se"
# Caso 1: verbo seguido de palabra (más común en frases)
for _v_formal, _v_tu in _VERB_TU.items():
    POST_PROCESS.append(
        (
            rf"\b{_v_formal}\b(?!\s+(?:usted|él|ella|ellos|ellas))(?=\s+(?:un|una|el|la|los|las|que|al|del|por|con|sin|su|tu|mi|tus|mis|sus|todo|toda|todos|todas|más|menos|muy|bastante|poco|este|esta|estos|estas|ese|esa|esos|esas|aquel|aquella|aquellos|aquellas|\d+|[a-záéíóúñ]+))",
            _v_tu,
        )
    )

# Caso 2: verbo al final de frase (".", "!", "?") o final de cadena
for _v_formal, _v_tu in _VERB_TU.items():
    POST_PROCESS.append((rf"\b{_v_formal}\b(?=[.!?]|$)", _v_tu))

# Caso 3a: "[Ss]e + (le/te/nos) + verbo en 2ª persona" → revertir a 3ª persona (impersonal)
for _v_formal, _v_tu in _VERB_TU.items():
    POST_PROCESS.append(
        (
            rf"\b[Ss]e\s+(?:le|te|nos|me|os|la|lo|las|los)\s+{_v_tu}\b",
            lambda m, f=_v_formal: m.group(0).rsplit(" ", 1)[0] + " " + f,
        )
    )

# Caso 3b: "[Ss]e + verbo en 2ª persona" (directo, sin pronombre intermedio)
for _v_formal, _v_tu in _VERB_TU.items():
    POST_PROCESS.append(
        (
            rf"\b[Ss]e\s+{_v_tu}\b",
            lambda m, f=_v_formal: m.group(0).rsplit(" ", 1)[0] + " " + f,
        )
    )
